### ISSUE TITLE
Feature Wish: HTML Tags Allowed by WYSIWYG Editor - Could We Include Fontawesome?

### ISSUE THREAD

**Issue by kleiner5Punkt** [slackero/phpwcms#114]
I know the WYSIWYG editor allows div-tags and that's pretty much it. I assume for a good reason. What I would like though is to use the tags of fontawesome or glyphicons - is there a work around?

<p class="myicon"><i class="fa fa-desktop"></i></p>?

**Comment by slackero** [comment]
It is a CKEditor enhancement and easy to configure based on your needs. HTML tags are allowed — guess you mean to allow empty HTML tags. Have a look at this http://ckeditor.com/addon/fontawesome.

The template/config/ckeditor/ckeditor.config.sample.js has some commented lines. Try to play with this.
