### ISSUE TITLE
Mit dem Update vom Wochenende 25.01. Anzeigefehler im Backend

### ISSUE THREAD

**Issue by kukki15344** [slackero/phpwcms#115]
Ich habe die am Wochenende gezogene Version heute neu aufgespielt. Im Backend werden die Versionsinformationen nicht mehr angezeigt:

![fehlerbackendinfo](https://cloud.githubusercontent.com/assets/6285517/5915307/7504ea42-a604-11e4-98db-f255fb275e1a.jpg)

**Comment by robinsherwood** [comment]
I cannot repeat this "error". All output is as normal as should be.

**Comment by kukki15344** [comment]
Das Gleiche ist auch mit einer völlig neu angelegten Seite - also kein Update! Habe vor zwei Tagen eine neue Seite nur erst einmal installiert und wollte eben dran arbeiten!
