### ISSUE TITLE
& wird im Seitentitel als &amp; ausgegeben

### ISSUE THREAD

**Issue by uwe367** [slackero/phpwcms#116]
Bennene ich eine Kategorie beispielsweise Abfall & Entsorgung, so wird das "&" im Seitentitel im Browser als "& amp;" ausgegeben. Getestet in IE, Firefox, Opera, Safari.
Ist das so richtig und mache ich evtl. einen Fehler oder habe etwas nicht beachtet oder ist das ein Bug?

phpwcms Version ist 1.7.6 (2015/01/16, r538).

Anbei ein Screenshot zum besseren Verständnis.
![screen](https://cloud.githubusercontent.com/assets/2964678/5925660/6b17d7a4-a665-11e4-9a94-87706bb75b66.jpg)

**Comment by slackero** [comment]
Systemseitig erfolgt das nicht. Vermutlich parst Du den Seitentitel noch durch eigenen Code und HTML-encodierst so nochmals.
