### ISSUE TITLE
Backend Profil neues Passwort wird nach 20 Zeichen abgeschnitten

### ISSUE THREAD

**Issue by a6k** [slackero/phpwcms#117]
Wenn man im Backend->Benutzerverwaltung ein neues Passwort für einen Benutzer festlegt und dieses länger als 20 Zeichen ist, dann werden nur die ersten 20 Zeichen gespeichert. Ohne Warnung/Hinweis denkt man, das das Passwort in kompletter Länge übernommen wird. Abmelden und erneutes Anmelden ist nicht möglich.

Es wär ein Hinweis hilfreich falls das Passwort länger als 20 Zeichen ist.

**Comment by slackero** [comment]
Normalerweise passierte das nicht. Alle Felder haben eine `maxlength` von 20 Zeichen definiert. Diese habe ich jedoch mit commit 1c7be63f403e42044ba3c6a2d11a33815603b1ee auf 50 erhöht.
