### ISSUE TITLE
A mistake since merging branch

### ISSUE THREAD

**Issue by jensensen** [slackero/phpwcms#120]
I think we're working on the wrong branch.

**'master' is the default branch.** After cloning the repro you work in 'master'.
But this branch is 7 commits behind 'modernize'. And 'modernize' actually is 7 commits ahead of 'master'.
**working [default] in 'master' git pull says: there's nothing new!**

#### You better would have merged 'modernize' into 'master', than 'master' into modernize, i think.

So by now, what is the branch we should pull from to work with our local clones?
Which branch can/should we use NOW on the web server?

**Comment by slackero** [comment]
I have renamed the branches, then it's clear (I guess). Use **master** branch only.
