### ISSUE TITLE
Fehler bei pull

### ISSUE THREAD

**Issue by jensensen** [slackero/phpwcms#121]
Wende an: Minor changes to the backend
Verwende Informationen aus der Staging-Area um einen Basisverzeichnis nachzustellen
M	include/inc_css/phpwcms.css
M	include/inc_lang/backend/de/lang.inc.php
M	include/inc_lang/backend/en/lang.inc.php
M	include/inc_lang/backend/fr/lang.inc.php
M	include/inc_lib/backend.functions.inc.php
M	include/inc_lib/general.inc.php
M	include/inc_lib/navi_text.inc.php
M	include/inc_tmpl/admin.groups.tmpl.php
M	include/inc_tmpl/admin.structform.tmpl.php
M	include/inc_tmpl/admin.templates.tmpl.php
M	include/inc_tmpl/be_start.tmpl.php
M	include/inc_tmpl/content/cnt2.inc.php
M	include/inc_tmpl/content/cnt22.inc.php
M	include/inc_tmpl/content/cnt23.inc.php
M	include/inc_tmpl/content/cnt26.inc.php
M	include/inc_tmpl/content/cnt51.inc.php
M	include/inc_tmpl/files.actions.tmpl.php
M	include/inc_tmpl/forum.list.tmpl.php
M	include/inc_tmpl/message.send.tmpl.php
M	phpwcms.php
Falle zurück zum Patchen der Basis und des 3-Wege-Merges...
automatischer Merge von phpwcms.php
KONFLIKT (Inhalt): Merge-Konflikt in phpwcms.php
automatischer Merge von include/inc_tmpl/message.send.tmpl.php
KONFLIKT (ändern/löschen): include/inc_tmpl/forum.list.tmpl.php gelöscht in Minor changes to the backend und geändert in HEAD. Stand HEAD von include/inc_tmpl/forum.list.tmpl.php wurde im Arbeitsbereich gelassen.
automatischer Merge von include/inc_tmpl/files.actions.tmpl.php
automatischer Merge von include/inc_tmpl/content/cnt51.inc.php
automatischer Merge von include/inc_tmpl/content/cnt26.inc.php
automatischer Merge von include/inc_tmpl/content/cnt23.inc.php
automatischer Merge von include/inc_tmpl/content/cnt22.inc.php
automatischer Merge von include/inc_tmpl/content/cnt2.inc.php
automatischer Merge von include/inc_tmpl/be_start.tmpl.php
automatischer Merge von include/inc_tmpl/admin.templates.tmpl.php
automatischer Merge von include/inc_tmpl/admin.structform.tmpl.php
automatischer Merge von include/inc_tmpl/admin.groups.tmpl.php
KONFLIKT (ändern/löschen): include/inc_lib/navi_text.inc.php gelöscht in Minor changes to the backend und geändert in HEAD. Stand HEAD von include/inc_lib/navi_text.inc.php wurde im Arbeitsbereich gelassen.
automatischer Merge von include/inc_lib/general.inc.php
automatischer Merge von include/inc_lib/backend.functions.inc.php
automatischer Merge von include/inc_lang/backend/fr/lang.inc.php
automatischer Merge von include/inc_lang/backend/en/lang.inc.php
automatischer Merge von include/inc_lang/backend/de/lang.inc.php
automatischer Merge von include/inc_css/phpwcms.css
Anwendung des Patches fehlgeschlagen bei 0001 Minor changes to the backend
Die Kopie des fehlgeschlagenen Patches befindet sich in:
   /home/user/dort/testg/phpwcms/.git/rebase-apply/patch

Wenn Sie das Problem aufgelöst haben, führen Sie "git rebase --continue" aus.
Falls Sie diesen Patch auslassen möchten, führen Sie stattdessen "git rebase --skip" aus.
Um den ursprünglichen Branch wiederherzustellen und den Rebase abzubrechen,
führen Sie "git rebase --abort" aus.

```
POST git-upload-pack (947 bytes)
POST git-upload-pack (702 bytes)
Von https://github.com/slackero/phpwcms
 * branch            master     -> FETCH_HEAD
   615e254..46261e4  master     -> origin/master
<stdin>:1229: space before tab in indent.
	      	case "profile":	//Profile
<stdin>:1230: space before tab in indent.
					      	if($p === 1) {
<stdin>:1231: space before tab in indent.
					      		include(PHPWCMS_ROOT.'/include/inc_tmpl/profile.data.tmpl.php');
<stdin>:1232: space before tab in indent.
					      	} else {
<stdin>:1233: space before tab in indent.
					      		include(PHPWCMS_ROOT.'/include/inc_tmpl/profile.account.tmpl.php');
warning: unterdrückte 93 Whitespace-Fehler
warning: 98 Zeilen fügen Whitespace-Fehler hinzu.
Merge der Änderungen fehlgeschlagen

```

**Comment by slackero** [comment]
Händisch lösen bzw. Merge in kleineren Schritten und wichtig: mögliche Konflikte lösen.
http://git-scm.com/book/de/v1/Git-Branching-Einfaches-Branching-und-Merging

Ansonsten neues Repository auschecken!

Wurden denn eigene Codeanpassungen vorgenommen?

**Comment by jensensen** [comment]
War ein 'frisches' Repository. Klappt aber jetzt. Vielleicht die Leitung. Keine Ahnung. Sorry und Danke für Deine Einschätzung.
