### ISSUE TITLE
Output in Listing Mode even when only one article to display

### ISSUE THREAD

**Issue by q23** [slackero/phpwcms#125]
if listing mode of category is enabled this only works if more than one (visible) article is available. cant imagine a good reason for this. please change to always listing if set.
![screenshot-www brennholz-plank de 2015-02-11 17-52-36](https://cloud.githubusercontent.com/assets/2988261/6151551/dc02b9b8-b216-11e4-8ff2-1529a30db046.png)

**Comment by slackero** [comment]
That's a long-term feature. **No change here**, but implemented `$template_default['settings']['force_article_list_mode']` in `conf.template_default.inc.php`. So you have the option to overwrite the behaviour globally or based on structure level.

**Comment by q23** [comment]
thx

**Comment by marcus-at-localhorst** [comment]
`$content['struct'][ $content['cat_id'] ]['acat_topcount']` is a string so `=== -1` fails

**Comment by slackero** [comment]
Fixed (I guess), see 2ebff3e7ba738904f29802ed24a1cd20879cb4aa
