### ISSUE TITLE
bootstrap switch and SYSTEM container

### ISSUE THREAD

**Issue by robinsherwood** [slackero/phpwcms#128]
If I try to put a bootstrap row into the {SYSTEM} container, the bootstrap switch isn't editable anymore (at least in my installation) and the sorting overview gets kind of confusing. How should I do?

**Comment by robinsherwood** [comment]
I just updated some installation to the latest...
Still / again any setting of "subsection" ist switching to "off" when placing this CP into the system container. Is this to be verified or some failing on my side?

**Comment by robinsherwood** [comment]
It seems that it isn't working for "group accordion" and "tabs" too

**Comment by slackero** [comment]
I cannot follow you — it is NOT possible to set ANY bootstrap row OR tab or accordion when block SYSTEM container is choosen.

**Comment by robinsherwood** [comment]
Right, it is not possible and hasn't been possible.
But: it has been possible for a short time (some weeks) to choose an item and then place it into SYSTEM and it didn't lose the selected item.
Before and after that short period and as for now it is losing the selected state and is switching to none...
That's what I mean ;)

**Comment by robinsherwood** [comment]
Just found out:
Even when I do NOT try to place a CP into this SYSTEM container it will always switch back to "off".
Meaning I cannot select any subsection at all...
