### ISSUE TITLE
Guestbook Timestamp

### ISSUE THREAD

**Issue by q23** [slackero/phpwcms#132]
The RT {TIMESTAMP:m/d/Y H:i} from  delivers date from today, not from date of guestbook entry.

**Comment by q23** [comment]
hi and thanks. but unfortunally it didnt work as expected. date is still from today.

**Comment by slackero** [comment]
here it is working as expected. I have checked twice including diverse var_dump to see what is coming in and if this is equal the current global value

**Comment by slackero** [comment]
Try yourself by replacing here:
https://github.com/slackero/phpwcms/blob/dfaea10823825262b157955434d9ee9fa5532d44/include/inc_front/content/cnt18.article.inc.php#L719

´´´
		if(!function_exists('guestbook_date_callback')) {
			function guestbook_date_callback($matches) {
				global $guestbook;
				dumpVar($guestbook['row']['guestbook_created']);
				return date($matches[1], empty($guestbook['row']['guestbook_created']) ? now() : $guestbook['row']['guestbook_created']);
			}
		}
		while($guestbook['row'] = mysql_fetch_assoc($guestbook['result'])) {
		
				dumpVar($guestbook['row']['guestbook_created']);
				
´´´

**Comment by q23** [comment]
sorry, not closed, yet. problem still exist. will get in touch with you soon.

**Comment by q23** [comment]
problem is guestbook in listing mode (categorie = 999). possible to fix this?

**Comment by slackero** [comment]
bit weird, it's a CP and not really meant to be used in listing mode. How do you do that, with {SYSTEM}?

**Comment by q23** [comment]
now it works. thank you.

> How do you do that, with {SYSTEM}?
we realize onepage with phpwcms in listing mode and a article-list-template with this:
{SHOW_CONTENT:CPA, {ARTICLEID} }

But {SYSTEM} would also be a possibility
