### ISSUE TITLE
Upset Varchar article_description

### ISSUE THREAD

**Issue by q23** [slackero/phpwcms#135]
Hello,

since we also use $article["article_description"] for
a. navi text output and
b. different language [de][en[jp]
255 signs is to less for this. to change in database is not enough - so we have a big problem with updates in the future.

so please change:
https://github.com/slackero/phpwcms/blob/1c7be63f403e42044ba3c6a2d11a33815603b1ee/include/inc_lib/article.editcontent.inc.php
Line 177
to make it possible to save more than 255 signs.
thank you, looking forward,
robert

**Comment by slackero** [comment]
It's far from what I would recommend for content editing and goes into the wrong direction. Avoid using [de][en][jp].

**Comment by q23** [comment]
cant tell customer to avoid if thats the only good solution that still exit for the cms. cat is biting in the tail, i guess

**Comment by slackero** [comment]
The cats have won!

**Comment by q23** [comment]
:D thanks. cats are very happy!

other enhancment could be to choose another field for nav-list-ul text-output

**Comment by slackero** [comment]
…better write custom function then

**Comment by q23** [comment]
to enhance the nav-list-ul output?

**Comment by slackero** [comment]
sometimes it is better to take this as basis, clone it — then strip functionality and enhance for own needs
