### ISSUE TITLE
Fehler bei Nutzung von Bildern im Texteditor

### ISSUE THREAD

**Issue by kukki15344** [slackero/phpwcms#136]
Um in einem Text (CP Text mit Bild) ein Icon einzufügen, hatte ich aus der Serverquelle ein Icon im Text verwendet. Nach dem Update V 1.7.8 war dieses verschwunden. Erneutes Einsetzen blieb erfolglos. Ich konnte folgende Fehlermeldung provozieren:

>Warning: require(/var/www/webxxx/html/wCMS//config/phpwcms/conf.inc.php) [function.require]: 
failed to open stream:
> No such file or directory in /var/www/webxxx/html/wCMS/img/cmsimage.php on line 15

>Fatal error: require() [function.require]: Failed opening required '/var/www/web310/html/wCMS//config/phpwcms/conf.inc.php' (include_path='.:/usr/local/php5.3/lib/php') in /var/www/webxxx/html/wCMS/img/cmsimage.php on line 15

**Comment by slackero** [comment]
es ist sinnvoll, beim Update alle Dateien zu aktualisieren, die zum System gehören, u.a. auch **img**

**Comment by q23** [comment]
*dateien im /img/ folder
