### ISSUE TITLE
shop API

### ISSUE THREAD

**Issue by robinsherwood** [slackero/phpwcms#140]
- line 245 to 248 commented
- line 293 to 294 three loops (}) copied upwards, that is directly beneath '$position['id'] = md5($item["shopprod_id"].$item['shopprod_ordernumber']);'

and all is running as expected (by now) ;)

**Comment by slackero** [comment]
Send a pull request

**Comment by robinsherwood** [comment]
done

**Comment by robinsherwood** [comment]
I've sent a pull request. Has it been done the right way?

**Comment by slackero** [comment]
it takes time to proof it … there wasn't yet

**Comment by robinsherwood** [comment]
No, I didn't mean to hurry, just wanted to be sure you didn't overlook it.
The little change within the api file is doing it's job quite well ;)
