### ISSUE TITLE
no update of number of items

### ISSUE THREAD

**Issue by robinsherwood** [slackero/phpwcms#142]
When I add an item to the shop it will be displayed as "1 item in basket"
So far so good.
Switching over to checkout:
When I change the number of items to 5 and update the cart and afterward go back via "go on shopping", there still the basket contains 1 item only.
I think that this is kind of a bug?

This will only happen if cart and shop are on different pages. With all in one page everything seems to be ok.

**Comment by slackero** [comment]
It never was different from that, it's the question what you count, each quantity or just the type of products

**Comment by robinsherwood** [comment]
Great! :)
