### ISSUE TITLE
[PAYBY_PREPAY] and so on isn't replaced correctly

### ISSUE THREAD

**Issue by robinsherwood** [slackero/phpwcms#144]
[PAYBY_PREPAY]Vorauskasse
Ihre Bestellung wird nach Zahlungseingang versendet
Überweisen Sie den Gesamtbetrag auf folgendes Konto:
Empfänger: xxx
IBAN: xxx[/PAYBY_PREPAY][PAYBY_POD]Nachnahme[/PAYBY_POD][PAYBY_ONBILL]

isn't replaced correctly (neither for the ordering person's mail nor for the shop owner's mail)

**Comment by robinsherwood** [comment]
This is an ongoing missing item and has never worked correctly (has nothing to do with any pimping attempts) ;)

**Comment by slackero** [comment]
It works as expected for order confirmation email, shop owner confirmation never had it implemented.
