### ISSUE TITLE
bug in selecting subsections and saving the selection

### ISSUE THREAD

**Issue by robinsherwood** [slackero/phpwcms#145]
A freshly unzipped "You are running phpwcms 1.7.8 (2015/03/24, r539)" switches to **OFF** again while trying to save the setting.
Neither can I push ohne of these selections into the SYSTEM container, of course.
This seems to be a bug (again) - also see https://github.com/slackero/phpwcms/issues/128

**Comment by slackero** [comment]
Your problem — no subsection title / no number = resets subsection to unselected. 

See commit f63ce6ccdd5fdeb369ef3526bcd22f5165b9219d

**Comment by robinsherwood** [comment]
Of course I set a subsection title / number but anyway it will switch to "off" - no matter what I'm trying out: tabs, acc, container.
