### ISSUE TITLE
branch master

### ISSUE THREAD

**Issue by jensensen** [slackero/phpwcms#147]
"master" steht seit 24 tagen auf 1066 commits.
würde nur gerne wissen, ob das so richtig ist?

vielen dank und grüße

**Comment by slackero** [comment]
dev-1 ist produktiv nutzbar, in ein paar Tagen ist die Übernahme in Master geplant. Mache erst ein Projekt fertig, aus dem immer wieder paar Änderungen eingeflossen sind.
