### ISSUE TITLE
CP Form mit mehr als 11 Feldern -> weißes Backend 

### ISSUE THREAD

**Issue by kleiner5Punkt** [slackero/phpwcms#154]
Ver. 1.8.0-RC2, r541 - ContenPart: Formular
Habe 11 Felder angelegt, wenn ich das 12. Feld anlege und aktualisiere bleibt das Backend weiß - kein Quelltext - alles leer, beim erneuten einloggen ist der CP vorhanden, kann aber nicht aufgerufen werden - Backend ist dann wieder schneeweiß - Frontend ist das Formular da mit allen bis dahin angelegten  Feldern vorhanden.

**Comment by slackero** [comment]
Kann ich nicht nachvollziehen. PHP Fehlerausgabe prüfen. Vermutlich aktualisierte PHP Version mit Limitierung hinsichtlich maximal zulässiger Anzahl an Input-Variablen, siehe http://php.net/manual/en/info.configuration.php#ini.max-input-vars

**Comment by kleiner5Punkt** [comment]
Hi Oliver,

PHP Fehlerausgabe vom Frontend ist

Notice: Undefined index: maxlength in /var/www/vhosts/.../httpdocs/00-cms-2015/include/inc_front/content/cnt23.article.inc.php on line 1027 Zeile 

in der Zeile steht 1027: 

 if($cnt_form['upload_value']['maxlength‘])


im Backend bleibt die weiße Seite - ich habe bei meinem Test reine einzeilige Textfelder eingegeben - trotzdem ist beim 12. Feld schluss wenn ich hier nach auf 




aktualisieren klicke  - hab ich nur noch eine weiße Seite 


Lieben Gruß
Steffi Raack


 eyelikeit - visual solutions 
steffi raack
arnheimer str. 16a 
d 40489 düsseldorf 
____________________________________________ 
phone:   +49 211 557 9112 
mobile:   +49 175 1585359
fax:         +49 211 557 9116 
____________________________________________ 
http://www.eyelikeit.com   
s.raack@eyelikeit.com

**Comment by slackero** [comment]
Das eine hat mit dem anderen nichts zu tun. Das Frontendproblem ist behoben
https://github.com/slackero/phpwcms/commit/9ef5a602513487bcc1bcfc7c0b2a0669c41e0f16

Bei dem Backendproblem siehe meinen Kommentar

**Comment by slackero** [comment]
Kein Feedback?
