### ISSUE TITLE
Contentpart CODE, first {SEGMENT} is ignored, the others going through well and untouched  1.8.0 RC1 

### ISSUE THREAD

**Issue by df6ih** [slackero/phpwcms#159]
in Contentpart "Code" filled in:

{TEST1}
{TEST2}
{TEST3}
{TESTn}

after rendering to:

{TEST2}
{TEST3}
{TESTn}

**Comment by robinsherwood** [comment]
CP Code seems to be "rendering as is"?, or not?

**Comment by df6ih** [comment]
Yes, 2 different Installs and 2 heads testing: First {ELEMENT} Trown out

**Comment by slackero** [comment]
Not really a bug, more a feature
