### ISSUE TITLE
phpwcms Versionsinformationen

### ISSUE THREAD

**Issue by uwe367** [slackero/phpwcms#160]
Nach der Installation der neuesten Version auf Localhost (PHP 5.6.3) zeigt sich im BE dieser Dialog bei der Versionsinformation im Startfenster.
![screen-shot-017](https://cloud.githubusercontent.com/assets/2964678/12073347/f9dbf616-b11b-11e5-85d7-17080fa6f303.jpg)

Bei Vorgängerversion tritt dieses Verhalten nicht auf.

**Comment by df6ih** [comment]
Same here

**Comment by slackero** [comment]
gefixt, habe die Domains auf phpwcms.org umgestellt, deshalb
