### ISSUE TITLE
Update-Prozedur ist nicht zeitgemäß ....

### ISSUE THREAD

**Issue by kukki15344** [slackero/phpwcms#162]
ich bin mehrfach darüber gestolpert, dass bei einem Update von 1.6x auf 1.82 einige verwendete Einstellungen/ RTs/ CPs nicht mehr (richtig) funktionieren. Häufig sind fehlende Eintragungen in der config.inc die Ursache. Es wäre daher angebracht, die Update-Prozedur dahin abzuändern, dass die fehlenden Einträge automatisch dazugefügt werden, wenn diese noch nicht vorhanden sind, incl. einem Hinweis, dass dort noch Anpassungen nötig sein könnten.

**Comment by q23** [comment]
ein update kann nie vollautomatisch laufen. da müssen manuell profis ans werk - die wissen was sie machen und was ggf. passieren kann. sehe ganz andere baustellen als diesen an sich guten ablauf optimieren zu müssen.

**Comment by tholu** [comment]
@q23 Bei Wordpress funktioniert das völlig problemlos.
