### ISSUE TITLE
Fehler am Ende der Installation

### ISSUE THREAD

**Issue by uwe367** [slackero/phpwcms#164]
Eben die neueste Version auf Localhost installiert und am Ende erhalte ich, wenn ich das BE aufrufe, folgende Fehlermeldungen:

**Warning: require_once(E:/xampp/htdocs/phpw4/phpw4/include/inc_lib/mimetype.inc.php): failed to open stream: No such file or directory in E:\xampp\htdocs\phpw4\include\inc_lib\default.inc.php on line 149**

**Fatal error: require_once(): Failed opening required 'E:/xampp/htdocs/phpw4/phpw4/include/inc_lib/mimetype.inc.php' (include_path='.;E:\xampp\php\PEAR') in E:\xampp\htdocs\phpw4\include\inc_lib\default.inc.php on line 149**

Anbei ein Screenshot wie es beim letzten Step der Installation aussieht:
![path-settings](https://cloud.githubusercontent.com/assets/2964678/13033686/495d0b64-d320-11e5-8b7b-67d321987973.jpg)

Nachdem ich mir die conf.inc.php anschaute sah es bei den Path Settings so aus:

**// paths
$phpwcms['DOC_ROOT'] = 'E:\xampp\htdocs\phpw4';**

Nachdem ich das manuell korrigierte:
**// paths
$phpwcms['DOC_ROOT'] = $_SERVER['DOCUMENT_ROOT'];**

läuft wieder alles.

Gerade noch auf Webspace (all-inkl.) getestet.
Es geschieht das gleiche und erst nach manueller Korrektur der conf.inc.php läuft das System.

Fehler evtl in der dist.conf.inc.php?
Bei Version vom 2016/01/29:  $phpwcms['DOC_ROOT']  = $_SERVER['DOCUMENT_ROOT']
Bei Version von heute          :  $phpwcms['DOC_ROOT']  = dirname(dirname(__FILE__))

**Comment by df6ih** [comment]
du installierst ja in ein Unterverzeichnis, gemessen vom Server... das kann man irgendwo (soweit ich weiß) im Install angeben,

**Comment by uwe367** [comment]
Hatte ich bisher nie angeben müssen. Wenn man die Installation in einem Unterverzeichnis durchführte suchte sich das System selbst den Pfad. Angeben mußte ich da nie etwas aber ich probiers gerne mal aus.

**Comment by df6ih** [comment]
als ich es geschrieben hatte, kamen Zweifel in mir auf :)

Jürgen Günther
http://guenther.it
Weinheimerstr 49
69469 Weinheim
+49 178 853 2305
Festnetznummer zum Handy:
06201-7303256
Fax: 06201-4693504
Ust ID.  DE168317135

Am 14. Februar 2016 um 17:40 schrieb Uwe Tholey <notifications@github.com>:
