### ISSUE TITLE
Article-ID in Article-Edit

### ISSUE THREAD

**Issue by geckse** [slackero/phpwcms#165]
![phpwcms_articleid_editmode](https://cloud.githubusercontent.com/assets/12199921/13079105/e644a434-d4c2-11e5-8bb4-4a2d0afb0d7b.png)

the article id should displayed in article-edit mode. (maybe in baseinformation to?) many of our clients didn't really know how to find them.. are there more ways than hovering an article in article-central or the URI to get the article id?

**Comment by q23** [comment]
nice idea with id after page-name.
