### ISSUE TITLE
Beim Übertragen von Artikeln werden Contentparts nicht mit übertragen

### ISSUE THREAD

**Issue by uwe367** [slackero/phpwcms#167]
Übertrage ich, wenn ich als Admin eingeloggt bin, einen Artikel an einen anderen User, so wird die Artikelbasis an den User übertragen. Im Artikel vorhandene Contentparts werden jedoch in diesem Zuge **nicht** übertragen. Diese muß sich der entsprechende User, dem der Artikel übertragen wurde, "holen" indem er den CP öffnet und erneut speichert. Erst **dann** werden ihm die Rechte an dem CP übertragen. Auch zu ersehen in der DB. Funktioniert zwar, ist aber umständlich und sicherlich nicht der richtige Weg.
Siehe auch meinen Beitrag dazu im Forum:
http://forum.phpwcms.org/viewtopic.php?f=2&p=146452#p146438

Es handelt sich dabei um die im Screenshot gezeigte Funktion
![screen shot](https://cloud.githubusercontent.com/assets/2964678/13450151/c4337b10-e032-11e5-975c-9d8b9acc4428.JPG)

**Comment by slackero** [comment]
Should be solved with issue #176
