### ISSUE TITLE
RT-JavaScript mit einzeiligen //Kommentaren wird nicht korrekt geparst ... (V.1.8 ff)

### ISSUE THREAD

**Issue by kukki15344** [slackero/phpwcms#168]
Bei einer Erweiterung mehrere Website ist mir aufgefallen, das Versionen ab V 1.8x den JavaScript-Code nicht krrekt parsen:
Aus `<!-- JS: //Kommentar zum Script  -->`
wird `<script src=" //Kommentar zum Script` 

In Versionen V 1.7x funktioniert das noch.

siehe auch hier: [http://forum.phpwcms.org/viewtopic.php?f=16&t=24859](url)

**Comment by slackero** [comment]
S sieht ein Kommentar aus

**Comment by q23** [comment]
wetten das bald kommt so funktionierts auch nicht ;)
 -->

**Comment by slackero** [comment]
```
  .-'---`-.
,'          `.
|             \
|              \
\           _  \
,\  _    ,'-,/-)\
( * \ \,' ,' ,'-)
 `._,)     -',-')
   \/         ''/
    )        / /
   /       ,'-'
```
