### ISSUE TITLE
Replace build in Frontend Setup: Template by File

### ISSUE THREAD

**Issue by q23** [slackero/phpwcms#170]
Very hard to work with build in File-Template. And even not the phpwcms logic.

Better to choose a file from template dir under /template/inc_cntpart/main (or something).

currently we solve this with frontend_init script:
`$block['maintext'] = file_get_contents(PHPWCMS_TEMPLATE.'/inc_cntpart/main/'.$block['maintext']);`

**Comment by marcus-at-localhorst** [comment]
I do this forever, works like a charm.

**Comment by q23** [comment]
and thats why it have to be part of core functionality :)

**Comment by geckse** [comment]
indeed! A <select> from all available .tmpl files would be even better.

**Comment by q23** [comment]
```
if (strpos($block['maintext'], '.php') !== false) {
	$block['maintext'] = file_get_contents(PHPWCMS_TEMPLATE.'/inc_cntpart/main/'.$block['maintext']);
}
```

**Comment by slackero** [comment]
Done.
