### ISSUE TITLE
CP-Formular und ID-Doppelungen

### ISSUE THREAD

**Issue by geckse** [slackero/phpwcms#171]
Ich hab hier auf einer Seite mehrere Contentparts Typ Formular und habe aus gründen der Einfachheit die Namen für zB. für das E-Mailfeld in jeden dieser Contentparts "email" genannt. Im Frontend erhalten die <input>-Elemente 1 zu 1 diese Namen als ID, was in meinem fall zu Id-Doppelungen führt.. 

Wäre es nicht besser, wenn die IDs nochmal an die Formular-ID oder der CP-ID gebunden wären? Alternativ muss ich nun nicht redundante Namen für meine E-Mailfelder verwenden...

**Comment by slackero** [comment]
Scheinbar sinnvoll, da auch Attribut `name` für Deinen Fall identisch. Ist eine grundsätzliche Frage. Würde mit dieser Änderung Probleme hinsichtlich Abwärtskompatibilität geben. Empfehle eher, Du passt Deine Feldnamen an.
