### ISSUE TITLE
phpwcms.php renders empty backend page.

### ISSUE THREAD

**Issue by eccentricworx** [slackero/phpwcms#177]
as from version 1.8.0 if you want to create/edit CP:Teaser from the backend, phpwcms.php renders an empty backend page (source-code: none; PHP Errors: none;) if the Teaser has to list more than ~4500 Articles for Teaser Creation. No editing, no creation of the CP TEASER/ARTICLE possible.
Older Versions are not affected.
Tested with PHP v5.5 & v5.6.

**Comment by slackero** [comment]
As discussed in the forum http://forum.phpwcms.org/viewtopic.php?f=1&t=24914 any update to your problem?
