### ISSUE TITLE
Schlüsselwörter und Beschreibung der Seitenebene werden nicht gespeichert

### ISSUE THREAD

**Issue by uwe367** [slackero/phpwcms#185]
In der Kategorieebene **HOME** werden Schlüsselwörter sowie die Beschreibung der Seitenebene nicht gespeichert. Man kann zwar in den Feldern Eingaben machen, jedoch weren diese beim speichern wieder entfernt.
Dieser Fehler, sofern es denn einer ist, bezieht sich ausschließlich auf die Ebene **HOME**, siehe Screenshot.
![screen-shot](https://cloud.githubusercontent.com/assets/2964678/19449764/3782b5d0-94a7-11e6-8263-71fa91940984.jpg)

Ich glaube zu wissen daß dies in früheren Versionen funktionierte.

Verwendete Version: phpwcms 1.8.4 (2016/09/29, r544)

**Comment by slackero** [comment]
Kann ich nicht nachvollziehen. Eventuell ist die Datei `include/config/conf.indexpage.inc.php`schreibgeschützt.

**Comment by uwe367** [comment]
Ok. Stimmt.  Datei- Verezichnisrechte stimmten nicht und das wiederum kann ich nicht nachvollziehen denn diese wurden von mir vor der Installation korrekt gesetzt und standen nun komplett so als haätte ich das Installtionspaket gerade erst zum Server übertragen.
Nunja.. Issue ist damit erledigt.
Trotzdem Danke.
