### ISSUE TITLE
Notice in Dateizentrale bei Einzelupload phpwcms 1.9.0-beta.1

### ISSUE THREAD

**Issue by uwe367** [slackero/phpwcms#187]
In der Dateizentrale wird eine Notice beim Einzelupload ausgegeben. Siehe Screenshot.
phpwcms 1.9.0-beta.1 (2016/11/17, r544)

![1](https://cloud.githubusercontent.com/assets/2964678/20439890/0a10c4ae-adbe-11e6-9e5d-e09cb613383d.jpg)

**Comment by q23** [comment]
unter php5.5 nicht

**Comment by uwe367** [comment]
Ich teste unter PHP 5.6.3

**Comment by slackero** [comment]
trat nur auf, wenn noch kein Keyword definiert war
