### ISSUE TITLE
Warning bei Installation phpwcms 1.9.0-beta.1

### ISSUE THREAD

**Issue by uwe367** [slackero/phpwcms#190]
phpwcms 1.9.0-beta.1 (2016/11/17, r544) neuestes Update.

Bei der Installation wird eine **Warning** ausgegeben.
Siehe Screenshot

![screen-shot-005](https://cloud.githubusercontent.com/assets/2964678/20454909/06a8f328-ae4e-11e6-9991-e87f257905b6.jpg)

Getestet auf Localhost PHP 5.6.3

**Comment by slackero** [comment]
es reicht wirklich, nur die Fehlermeldung zu posten
