### ISSUE TITLE
Merkwürdiges Verhalten in der Dateizentrale phpwcms 1.9.0-beta.1

### ISSUE THREAD

**Issue by uwe367** [slackero/phpwcms#192]
Folgendes Beispiel:
Ich erstelle in der Dateizentrale im Wurzelverzeichnis ein Unterverzeichnis, z.B Test, und lade in dieses Dateien. Bei einem Klick auf das Pfeilsymbol, um dieses Verzeichnis (Test) zu öffnen, verschwindet dieses Verzeichnis und dann sieht es in der Dateizentrale so aus:

![1](https://cloud.githubusercontent.com/assets/2964678/20455919/c1441816-ae67-11e6-8e44-1aee046ffe2c.jpg)

Das Verzeichnis **Test** wird einfach ausgeblendet.

Erst nach einem erneuten Klick auf **Eigene** erscheint das Verzeichnis wieder und ist dann auch geöffnet. Genauso verhält es sich beim schließen.
Dateien, die im Wurzelverzeinis liegen, werden dabei nicht ausgeblendet.

Normalzustand:
![3](https://cloud.githubusercontent.com/assets/2964678/20455932/49544f14-ae68-11e6-8a9a-e3fb5212b7d5.jpg)

Und so sieht es aus wenn ich das Verzeichnis **Test** aufklappen möchte:
![4](https://cloud.githubusercontent.com/assets/2964678/20455942/63c05ec4-ae68-11e6-9ee5-9cf8cc3e8e7b.jpg)

Ich hoffe ich habe das verständlich erklärt und der Fehler ist reproduzierbar.

**Comment by slackero** [comment]
Kann ich nicht nachvollziehen. Möglicherweise schon mit anderem Fix gelöst.

**Comment by uwe367** [comment]
> Kann ich nicht nachvollziehen. Möglicherweise schon mit anderem Fix gelöst.

Sieht ganz danach aus. Verhalten tritt nicht mehr auf.
Danke
