### ISSUE TITLE
PHP 7.0 Support?

### ISSUE THREAD

**Issue by TinuCH1976** [slackero/phpwcms#194]
I'm not sure, if I did a mistake. But I didn't get it to work on PHP 7 (Setup hangs on first Page, after the text MySQL-Version the side stops)

**Comment by slackero** [comment]
You have taken the [1.9-dev branch](https://github.com/slackero/phpwcms/tree/v1.9-dev)?

**Comment by TinuCH1976** [comment]
nope, I'm the following version/nein, benutze die folgende Version:
phpwcms 1.8.4 (2016/09/29, r544)

now with php 5.4 it works / jetzt mit PHP 5.4 funktioniert es

**Comment by slackero** [comment]
take 5.6 not 5.4! 5.4 should have never been used.
