### ISSUE TITLE
Keine vorgefertigten CSS-Styleangaben in CP-Templates mehr!

### ISSUE THREAD

**Issue by kukki15344** [slackero/phpwcms#195]
Mit dem neueren Flexbox-Modell ergeben sich einige Probleme, die die modernere Anwendung - vor allem mit den CP-Standard-Templates erschweren. Alle bisherigen CSS-Styleangaben sollten in **einer** externen allgemeingültigen frontend.css stehen,  ich mein damit wirklich **alle**, die bei nächsten Update nicht wieder drübergebügelt werden. Nur so wird es künftig möglich sein, neben dem noch verbreiteten Float-Modell auch entsprechende Flex-Box-Modelle mit externen CSS-Style-Vorlagen und Index.Templates- auch für ein Flex-Box-Lösung - zur Verfügung zu stellen.

**Comment by slackero** [comment]
CSS kann nach Belieben angepasst werden. Es gibt kein verbindliches CSS, wenn solche Anweisungen enthalten sind, dienen diese vor allem als Beispiel.
