### ISSUE TITLE
Please merge changes of master-branch (or vice versa)

### ISSUE THREAD

**Issue by q23** [slackero/phpwcms#199]

**Comment by slackero** [comment]
Done!

**Comment by q23** [comment]
not completed. see e.g. include/inc_lib/dbcon.inc.php for difference

**Comment by slackero** [comment]
I will not back port changes in v1.9-dev to the master (v1.8) branch.

**Comment by q23** [comment]
no problem, but maybe from master to v1.9 *liebguck

**Comment by slackero** [comment]
>  but maybe from master to v1.9
@q23 ist doch

**Comment by q23** [comment]
mea culpa
