### ISSUE TITLE
2 Notice´s beim erstellen eines neuen CP´s

### ISSUE THREAD

**Issue by uwe367** [slackero/phpwcms#200]
Beim erstellen eines neuen CP´s erhalte ich 2 Notice Meldungen.

> Notice: Undefined index: livedate in E:\xampp\htdocs\test\include\inc_tmpl\articlecontent.edit.tmpl.php on line 34
Notice: Undefined index: killdate in E:\xampp\htdocs\test\include\inc_tmpl\articlecontent.edit.tmpl.php on line 40
> 
Und im CP bei den neuen Datumsfeldern sieht es dann so aus:
![cp](https://cloud.githubusercontent.com/assets/2964678/22436254/a897fedc-e723-11e6-96e7-dff1402f47de.jpg)
Es spielt dabei keine Rolle welchen CP ich erstelle, die Meldungen erscheinen bei allen.
Version: phpwcms 1.8.6 (2017/01/30, r545)

**EDIT:**
Die Meldungen werden nur beim erstmaligen erstellen eines CP ausgegeben. Besteht ein CP, so werden die Meldungen beim erstellen eines neuen CP nicht mehr angezeigt.

**Comment by slackero** [comment]
Was just solved with commit 2162e0a28c79a2e6fd76fec2672fb8c11faeab7d.
