### ISSUE TITLE
dev_1.9: Fatal error: Validating the CSRF token failed, probable an outdated request.

### ISSUE THREAD

**Issue by q23** [slackero/phpwcms#203]
Saving CP-Detail-Page is possible without any error.
Saving any Contentparts leads to a reload of page without saving changes in database. Reload page after that manually leads to:
Fatal error: Validating the CSRF token failed, probable an outdated request. in /include/inc_lib/helper.session.php on line 443
on 1&1 server. system is up to date wie dev4-1.9

**Comment by q23** [comment]
PHP Version 7.0.10 & 7.1.1

**Comment by q23** [comment]
Warning: Cannot modify header information - headers already sent by (output started at /include/inc_lib/default.inc.php:553) in /phpwcms.php on line 219

**Comment by slackero** [comment]
I cannot confirm this specific behaviour. Works well here. Maybe this helps:

1. Logout
2. delete all `/content/tmp/*.tmp` files
3. Login again

I guess some db fields are missing or something else.

**Comment by q23** [comment]
yes, solves the problem. thank you very much.
when switching from "old" version to dev this seems to be neccessary.
