### ISSUE TITLE
[CAPTION_SUPPRESS_ELSE][CAPTION_SUPPRESS_ELSE] not rendering

### ISSUE THREAD

**Issue by robinsherwood** [slackero/phpwcms#205]
I use the standard <l i ></ li> teaser template with a random article title listing and get this result:
.......Ländertreffen 2016 [CAPTION_SUPPRESS_ELSE][CAPTION_SUPPRESS_ELSE]
Seems to have a render issue?

**Comment by slackero** [comment]
Are you sure?
`[CAPTION_SUPPRESS_ELSE][/CAPTION_SUPPRESS_ELSE]`

**Comment by robinsherwood** [comment]
Quite, yes.
Just detected: The default says:
`<!-- Caption is suppressed -->[/CAPTION_SUPPRESS][CAPTION_SUPPRESS_ELSE][CAPTION]<p>{CAPTION}</p>[/CAPTION][CAPTION_SUPPRESS_ELSE]`

**Comment by robinsherwood** [comment]
Easy to fix ;)

**Comment by slackero** [comment]
Your closing tag is wrong!!! Do not forget the slash `/`
`[/CAPTION_SUPPRESS_ELSE]`
There is nothing to fix

**Comment by robinsherwood** [comment]
This is what I copied from the default teaser at github an hour ago, it's not my construction ;)
There indeed the slash is missing - adding it solved the problem right away

**Comment by slackero** [comment]
Next time open the issue right next to the CP teaser and show me the [line](https://github.com/slackero/phpwcms/blob/master/template/inc_default/teaser.tmpl#L14) with corrected code if possible. I couldn't get exactly what was wrong from your description…
