### ISSUE TITLE
Branch v1.9-dev -- get no revision r545 checked in /content/tmp

### ISSUE THREAD

**Issue by jensensen** [slackero/phpwcms#206]
I came from master to v1.9-dev to get a copy of my project that is working perfect with php version 7 now. Really cool!!!
After logging in there should be a new file, named r544.checked.tmp in /content/tmp , but it isn't.

**Comment by slackero** [comment]
empty all `r*.checked.tmp` in `/content/tmp` then login again

**Comment by slackero** [comment]
Is working as expected, use latest release

**Comment by jensensen** [comment]
Sorry, "empty all r*.checked.tmp" - did you mean delete or empty?
When I delete all the files in /content/tmp and then call the login.url I get:
r401.checked.tmp
r403.checked.tmp
r406.checked.tmp
r414.checked.tmp
r416.checked.tmp
r421.checked.tmp
r427.checked.tmp
r438.checked.tmp
r497.checked.tmp
r502.checked.tmp
r509.checked.tmp
r514.checked.tmp
r528.checked.tmp
r529.checked.tmp
r532.checked.tmp
r533.checked.tmp

Remember that I am already using the latest  v1.9-dev.

**Comment by slackero** [comment]
The latest of the 1.9 dev branch is always https://github.com/slackero/phpwcms/archive/v1.9-dev.zip
