### ISSUE TITLE
CP Image with text: RT {IMAGE} is wrong renderd in cimbination with {CAPTION}

### ISSUE THREAD

**Issue by photojo** [slackero/phpwcms#207]
**I have this in the template**

```
[TITLE]
       <div class="col-xs-12">
            <h3>{TITLE}</h3>[SUBTITLE]
            <h4>{SUBTITLE}</h4>[/SUBTITLE]
         </div>[/TITLE][TITLE_ELSE][SUBTITLE]
        <div class="col-xs-12">
            <h4>{SUBTITLE}</h4>
         </div>[/SUBTITLE][/TITLE_ELSE][IMAGE]
        <div class="col-xs-12 col-md-12">
            <figure class="img-responsive">
                     [ZOOM]<a href="img/cmsimage.php/1000x1000/{IMAGE_HASH}.{IMAGE_EXT}" rel="lightbox" data-do="zoom" 
               class="zoom-image"[IMAGE_TITLE] title="{IMAGE_TITLE}"[/IMAGE_TITLE][IMAGE_TITLE_ELSE][/IMAGE_TITLE_ELSE] > [/ZOOM]
{IMAGE}
[ZOOM]</a>[/ZOOM]
           [CAPTION]
                <figcaption>
                  <div class="image-caption">{CAPTION}  </div>[COPYRIGHT], <span class="copyright">{COPYRIGHT}</span>[/COPYRIGHT]
                </figcaption>[/CAPTION]
            </figure>
         </div>[/IMAGE][TEXT]
        <div class="col-xs-12">
          {TEXT}
         </div>[/TEXT]
```

Everthing works fine, if "Vorschaubilder ohne Bildunterzeile" is DISABLED. But, if it is ENABLED, the link contains the image AND the text ({TEXT})

**Here is the resulting source-code:**

             <a href="img/cmsimage.php/1000x1000/119fa78dec46e43e3c4b64b889e4c211.jpg" rel="lightbox" data-do="zoom" class="zoom-image" > 
<i m g src="img/cmsimage.php/1200x800x0/119fa78dec46e43e3c4b64b889e4c211.jpg" alt="
**broken end of link**</a>
       
            </figure>
         </div>
        <div class="col-xs-12" style="border: 1px solid red;">
           <p>TEXT aus BE</p>
<p>text text ... text</p>

**Comment by slackero** [comment]
Nicht nachvollziehbar. Nutze aktuelle Version.
