### ISSUE TITLE
Bug: backend/de/lang.inc.php

### ISSUE THREAD

**Issue by grieselbaer** [slackero/phpwcms#208]
Hello!

After a clean install of the actual github version on two different servers I got only a blank white login.php page and this error:
PHP Parse error:  syntax error, unexpected '[' in /include/inc_lang/backend/de/lang.inc.php on line 1030

After change this line from
$BL['be_admin_optgroup_label'] = [1 => 'Text', 2 => 'Bild', 3 => 'Formular', 4 => 'Admin', 5 => 'Spezial'];
to
$BL['be_admin_optgroup_label'] = array(1 => 'Text', 2 => 'Bild', 3 => 'Formular', 4 => 'Admin', 5 => 'Spezial');
everything seems ok

Bye 
grieselbaer

**Comment by slackero** [comment]
Do not use outdated PHP versions for new installations, I recommend PHP 5.6 for older branch. [] instead of array() is supported since 5.4 http://php.net/manual/de/migration54.new-features.php
