### ISSUE TITLE
Deprecated in /include/inc_lib/news.inc.php bei PHP7.0.6

### ISSUE THREAD

**Issue by topixel** [slackero/phpwcms#209]
Im Backend unter Artikel>News bekomme ich folgende Warnung angezeigt:
`Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; phpwcmsNews has a deprecated constructor in [...] /include/inc_lib/news.inc.php on line 22`

Version ist phpwcms 1.9-dev vom 3. Mai.
Auf dem Server läuft PHP 7.0.6

**Comment by slackero** [comment]
should be fixed
