### ISSUE TITLE
CP: Bilder Spezial: Probleme bei Bildergänzungen

### ISSUE THREAD

**Issue by topixel** [slackero/phpwcms#210]
Beim Content-Part "Bilder Spezial" wird beim speichern (oder aktualisieren) nur ein Objekt gesichert. 
Beim Hinzufügen neuer Objekte innerhalb des CP werden neu geöffnete Bilder auch immer dem obersten Objekt zugewiesen, auch wenn man das Datei-Icon aus den unteren Objekten verwendet. 
Beim öffnen des CPs vermisse ich auch die Miniaturbilder die nur beim Einbinden neuer Bilder angezeigt werden.
(Vorhandene "Bilder Spezial" die vor dem Update ergänzt wurden haben noch alle Bilder.)

Version ist phpwcms 1.9-dev v5
Auf dem Server läuft PHP 7.0.6

**Comment by slackero** [comment]
Fixed
