### ISSUE TITLE
CP: Bilder Spezial: Problemchen 2

### ISSUE THREAD

**Issue by topixel** [slackero/phpwcms#211]
Jetzt wo ich wieder mehrere Objekte einfügen kann, fällt mir auf, dass auch die Sortierfunktion nicht mehr da ist. 
(Früher gab es auch einen Rollover-Effekt für jedes Objekt im CP und eine gestrichelte Trennlinie. Das hat es bei irgendwelchen Umstellungen scheinbar auch zersemmelt.)
(Und Danke noch für deine schnelle Reaktion vorhin. 👍 )

**Comment by slackero** [comment]
Du musst Deine CSS aktualisieren und mal Browsercache leeren, ich habe das neulich von `<li>` auf `<div>` umgebaut. Deswegen auch das andere Problem, ein JavaScript Selektor war nicht angepasst worden.
