### ISSUE TITLE
No input file specified.

### ISSUE THREAD

**Issue by q23** [slackero/phpwcms#213]
Msg appears when trying to use new Resized image /img/cmsimage.php/… -> /im/… Function on apache/ PHP Version 7.1.6

**Comment by q23** [comment]
guess this is "the problem":
# Resized image /img/cmsimage.php/… -> /im/…
RewriteRule ^im\/(.+?)$ ./img/cmsimage.php/$1 [L]

on other systems this works as expected.

**Comment by slackero** [comment]
Cannot follow, what is the problem?

**Comment by slackero** [comment]
Maybe rewrite against
`RewriteRule ^im\/(.+?)$ ./img/cmsimage.php?$1 [L]`

**Comment by slackero** [comment]
Check the commit 947255634498165b654bcc8c0309a556eb7beba3 please.

**Comment by q23** [comment]
- the messages comes from apache, thats why i prompt the .htaccess rule
- rewrite again did not solve the problem
- the commit 9472556 also

(- i know that this version is not recommend for a productiv system, thats why we use it on dev stage)

**Comment by slackero** [comment]
Then proof why your Apache is not able to handle the rewrite against cmsimage.php

**Comment by q23** [comment]
this alone (without the 'old' rule) does the trick on one specific server:
RewriteRule ^im\/(.+?)$ ./img/cmsimage.php?$1 [L]

!!! pay attention to questionmark instead of slash after .php !!!
