### ISSUE TITLE
image upload mysql-error f_cat has no default value

### ISSUE THREAD

**Issue by jensensen** [slackero/phpwcms#215]
Maybe it should has happen earlier, but I got it today.

Could solve by executing:
ALTER TABLE `phpwcms_file` CHANGE `f_cat` `f_cat` VARCHAR(255) NOT NULL DEFAULT '0';

I'm using v1.9-dev latest.

**Comment by slackero** [comment]
No need, is default for new installs. Do not use MySQL in STRICT mode. But correct would be:
`ALTER TABLE phpwcms_file CHANGE f_cat f_cat VARCHAR(255) NOT NULL DEFAULT '';`
