### ISSUE TITLE
No input file specified.

### ISSUE THREAD

**Issue by topixel** [slackero/phpwcms#216]
Die in den Meta-Angaben erzeugte Bild-URL 
`<meta property="og:image" content="http://[example.org]/im/500x500x0/52ed7ad3e9d91781e7cbc9a1be239a06.png">`
gibt nur einen kurzen Fehlermeldungs-Text aus: "No input file specified."

phpwcms 1.9.0-beta.7 (letzte Woche frisch installiert.)

**Comment by slackero** [comment]
Do not forget updating your .htaccess file

**Comment by topixel** [comment]
The rewrite rules are not changed and are equal to the current version.

Both of your links works. 
How should I change the .htaccess Rewrite?

**Comment by slackero** [comment]
Have a look [here](https://github.com/slackero/phpwcms/blob/v1.9-dev/_.htaccess#L58)

**Comment by topixel** [comment]
Exactly the line also looks at my file. 
Could I have done something else wrong?

**Comment by slackero** [comment]
Check RewriteBase and also check Apache error log when accessing
`http://[example.org]/im/500x500x0/52ed7ad3e9d91781e7cbc9a1be239a06.png`

**Comment by topixel** [comment]
OK, I've swapped 
`    RewriteRule ^im\/(.+?)$ ./img/cmsimage.php/$1 [L]`
for 
`    RewriteRule ^im\/(.+?)$ ./img/cmsimage.php?$1&%{QUERY_STRING} [L]`
and now it seems to work. 

... Or do I now have problems elsewhere?

**Comment by slackero** [comment]
No, but your Apache Index options are not set well – but it's OK. I will make a note inside the _.htaccess file.
