### ISSUE TITLE
http://example.com/.html bei Meta-Angaben

### ISSUE THREAD

**Issue by topixel** [slackero/phpwcms#220]
Bei der Startseite erhalte ich folgende Zeile im Head:
`<meta property="og:url" content="http://example.com/.html">`

Die Adresse ist aber nicht aufrufbar und erzeugt einen Zugriffsfehler. rewrite_url ist aktiv und rewrite_url steht auf '.html'.

Aktuell verwendete Version phpwcms 1.9.0-beta.7 (2017/06/23, r548).

**Comment by slackero** [comment]
Ah damn, used false issue number, is fixed with commit 0660f890e0f2b2769bae9914a5ac93c7aa64cfa6
