### ISSUE TITLE
Max Input Lenght Fields

### ISSUE THREAD

**Issue by q23** [slackero/phpwcms#221]
Any Reason for this "short" input length
https://github.com/slackero/phpwcms/blob/833f5a3f215b9411c73f07b5e2a56a61103cff64/include/inc_tmpl/admin.structform.tmpl.php#L144
or 'alte zöpfe'?

**Comment by slackero** [comment]
Alte Zöpfe. In times of UTF-8 there is also no reason any longer for a-z-and-0-9…

**Comment by q23** [comment]
should i push changes?

**Comment by slackero** [comment]
If you have…

**Comment by q23** [comment]
thanks. you're faster than me

**Comment by q23** [comment]
hi, please allow more than 255 digits here
https://github.com/slackero/phpwcms/blob/f1a6a87da373eb3bde0696c7385e3a04f0441836/include/inc_lib/article.editcontent.inc.php#L194

**Comment by q23** [comment]
mille grazie
