### ISSUE TITLE
DOCTYPE_LANG anhand der Sprache des Artikels setzen [feature wish]

### ISSUE THREAD

**Issue by topixel** [slackero/phpwcms#225]
Nach W3C-Empfehlung sollte das lang-Attribut am Anfang einer HTML-Datei das Sprachkürzel der Sprache des enthaltenen Seiteninhaltes enthalten. 
Daher fände ich es sinnvoll, wenn dies automatisch von der eingestellten Sprache des gerade aufgerufenen Artikels gesetzt würde.

**Comment by slackero** [comment]
Bisher erfolgt das eher global. Das müsste noch mal überdacht werden, ob das diesen Wert überschrieben darf, bzw. wie damit umgegangen werden soll.
