### ISSUE TITLE
Variable PHPWCMS_RESIZE_IMAGE  is defined wrong

### ISSUE THREAD

**Issue by julianscheideggerleanuxch** [slackero/phpwcms#228]
After updating to 1.9R2 some image links failed.
wrong generatet link
/im/600x400/231.jpg

I think it should be.
define('PHPWCMS_RESIZE_IMAGE', 'img/cmsimage.php');

https://github.com/slackero/phpwcms/blob/c50074c9c294c2e00dfecc8399e09c69f44f066a/include/inc_lib/default.inc.php#L150

**Comment by q23** [comment]
thats right. see .htaccess
    # In case of config setting `$phpwcms['rewrite_url']=1` (Default)
    # ===============================================================
    # Resized image /img/cmsimage.php/… -> /im/…
    #RewriteRule ^im\/(.+?)$ ./img/cmsimage.php/$1 [L]
	RewriteRule ^im\/(.+?)$ ./img/cmsimage.php?$1 [L]
