### ISSUE TITLE
URL Ausgabe bei Verwendung eines SSL Zertifikats fehlerhaft

### ISSUE THREAD

**Issue by uwe367** [slackero/phpwcms#229]
Version : phpwcms 1.9.0-rc.2 (2017/11/29, r549)
Binde ich ein SSL Zertifikat ein, z.B. eines von Let´s Encrypt, so wird bei Aufruf der Seite in der Adressleiste des Browsers folgendes ausgegeben:

`https://www.neu.uwe367.de/http://www.neu.uwe367.de/`
Siehe hier: http://www.neu.uwe367.de

In einer älteren Installation, wie phpwcms 1.9.0-beta.4 (2017/04/29, r545),  funktioniert dies jedoch einwandfrei.
Siehe hier: http://www.test.uwe367.de/
Siehe auch im Forum:
https://forum.phpwcms.org/viewtopic.php?f=16&p=148364#p148364

**Comment by slackero** [comment]
Erstmal hat das nichts mit dem Zertifikat an sich zu tun.

Die Konfiguration an sich sollte so aussehen, wie ist Deine?
```
$phpwcms['site'] = '';
$phpwcms['site_ssl_mode'] = 1;
$phpwcms['site_ssl_url'] = '';
$phpwcms['site_ssl_port'] = 443;
```

Für mich sieht das eher nach einer falschen Konfiguration der .htaccess aus.

**Comment by uwe367** [comment]
Die .htaccess ist nicht aktiv, also auf dem Server _.htaccess und das bei BEIDEN Installationen.
Die Konfiguration der conf.inc.php sieht bei mir so aus wie du es zeigst.
Von daher weiß ich nicht was ich noch tun soll.

Bei der älteren Version klappts, bei der neuen leider nicht bzw. es wird die "normale" Url an die SSL  Url angehangen..

**Comment by slackero** [comment]
Du hast Dir irgendwo eine Weiterleitung reingebaut.

**Comment by uwe367** [comment]
Es handelt sich hierbei (bei der neuen phpwcms Version) um eine neue Standartinstallation mit Standarttemplate welches sich im Originalzustand befindet und auch sonst habe ich an der Installation nichts verändert, entfernt oder hinzugefügt.

**Comment by uwe367** [comment]
Habe gerade eben noch ein paar Versuche gemacht und an der htaccess liegts definitiv nicht.
Mit aktiver htaccess und aktiviem SSL wird die http Url an die https Url angehangen und das kann nicht funktionieren.
Mit deaktivierter htaccess und aktivem SSL die Url beim Aufruf der Startseite folgender maßen angezeigt:
`https://neu.uwe367.de/index.php?`
Für mich sieht es aus als würde hier irgendwo etwas fehlgeleitet.

**Comment by q23** [comment]
Konnten wir hier auch reproduzieren. Manipulation an der .htaccess hat es dann beseitigt.

**Comment by uwe367** [comment]
Darf ich fragen wie deine Manipulation aussieht?

**Comment by slackero** [comment]
Bitte mal testen, ob das Problem mit der kleinen Änderung final bei Euch gelöst ist.

**Comment by uwe367** [comment]
Danke für deine Mühe Oliver.
Gerade in der neuen Version getestet.
Mit aktiver .htaccess und rewrite klappts nun, mit inaktiver .htaccess (also _.htaccess) wird die Url folgendermaßen ausgegeben:
`https://neu.uwe367.de/index.php?`

**Comment by robinsherwood** [comment]
Mit aktiver htaccess ohne rewrite bekomme ich das gleiche .../index.php?

**Comment by slackero** [comment]
ja und, wo ist das Problem :) – ist ja nicht falsch. Habe noch einen Check integriert, der das abfangen sollte

**Comment by uwe367** [comment]
Ne.. genrell falsch ist das nicht da ja die richtige Funktion gegeben ist. Sieht halt nur komisch aus wenn beim Startseitenaufruf ein /index.php? angehangen wird ;)
Danke fürs schnelle bearbeiten :)

**Comment by robinsherwood** [comment]
dann hole ich mir die Korrektur auch gleich - danke! :)

**Comment by q23** [comment]
danke auch von hier!
