### ISSUE TITLE
Alias der Seiten Ebene wird automatisch mit Umlaut ausgegeben

### ISSUE THREAD

**Issue by uwe367** [slackero/phpwcms#230]
Ist das so gewollt oider ein Fehler?
Beim erstellen einer neuen Seitenebene wird der Alias jetzt mit Umlaut augegeben, siehe Screenshot.
In früheren Versionen war es so, daß der Umlaut automatisch umgewandelt wurde 
(aus ü wurde automatisch ue).
Version: phpwcms 1.9.0-rc.2 (2017/12/21, r549)
![ebene](https://user-images.githubusercontent.com/2964678/34437252-032423b0-ec9d-11e7-9e7d-1033ce5bb7b9.jpg)

**Comment by slackero** [comment]
Das ist gewollt und kann in der Config beeinflußt werden, ist jetzt Standard: `$phpwcms['alias_allow_utf8'] = 1;`

Damit sind nun auch non-ASCII Alias möglich, z.B. auch Russisch usw.

**Comment by uwe367** [comment]
Ok. Danke für die Info.
Guten Rutsch ;)
