### ISSUE TITLE
Files with special characters: template/template_lang/*.php

### ISSUE THREAD

**Issue by tholu** [slackero/phpwcms#232]
The file `template/template_lang/*.php` seems to get autogenerated from time to time in one of the phpwcms installations I inherited.

Why and how does this happen? To use special characters like `*` in a filename is obviously a bad choice and should be avoided.

**Comment by slackero** [comment]
Setup your installation correctly. As long you accept any browser language as default. `*` is no special char. Use `$phpwcms['i18n_parse'] = 0` and it is gone.

**Comment by tholu** [comment]
> * is no special char.

Try running `rm *.php` on Linux. `*` needs to be escaped properly (`rm \*.php`), hence it is a special char.
Thanks for suggestion on how to fix this, will try that.

**Comment by slackero** [comment]
It's like in filenames with spaces. When it is a string, mark it as string `'*.php'` or escape it. It's no special char in the context of regular file operations in PHP. It's different with `.`, `..`, `/`, `:`

**Comment by tholu** [comment]
@slackero You are definitely right, without [glob()](http://php.net/manual/de/function.glob.php) PHP handles this as a normal filename. 

Thank you for changing this, this makes life easier outside of PHP!
