### ISSUE TITLE
Option to Anonymize IP

### ISSUE THREAD

**Issue by marcus-at-localhorst** [slackero/phpwcms#237]
With the coming GDPR, there should be an option to anonymize the IP address e.g. when saving form results in DB like here: https://github.com/slackero/phpwcms/blob/999c9705f6b412a173485f3496fd809f4e37b5b5/include/inc_front/content/cnt23.article.inc.php#L1884

I propose something like this:
https://github.com/slackero/phpwcms/blob/0ae8a05cb0e3ae3b26f472977c81b463b784aef2/include/inc_lib/default.inc.php#L894

```php
function getRemoteIP($anonymize = false) {
	if(defined('REMOTE_IP')) {
		return REMOTE_IP;
	}
	$IP = 'unknown';
	if (!empty($_SERVER['HTTP_CLIENT_IP']) && strcasecmp($_SERVER['HTTP_CLIENT_IP'], 'unknown')) {
		$IP = $_SERVER['HTTP_CLIENT_IP'];
	} elseif (!empty($_SERVER['HTTP_X_FORWARDED_FOR']) && strcasecmp($_SERVER['HTTP_X_FORWARDED_FOR'], 'unknown')) {
		$IP = $_SERVER['HTTP_X_FORWARDED_FOR'];
	} elseif (!empty($_SERVER['REMOTE_ADDR']) && strcasecmp($_SERVER['REMOTE_ADDR'], 'unknown')) {
		$IP = $_SERVER['REMOTE_ADDR'];
	}

	if($anonymize) {
		$IP = anonymize_ip($IP);
	}

	define('REMOTE_IP', $IP);
	return $IP;
}

// source: https://gist.github.com/svrnm/3a124d2af18a6726f66e
// anonymize_ip('76.97.51.109') => 76.97.0.0
// anonymize_ip('2601:c2:4004:57d0:257d:b9ba:4b1e:baac') => 2601:c2:4004:57d0::
function anonymize_ip($ip) {
	if($ip = @inet_pton($ip)) {
		return inet_ntop(substr($ip, 0, strlen($ip)/2) . str_repeat( chr(0), strlen($ip)/2 ));
	}
	return '0.0.0.0';
}
```

Best, Marcus

Edit: Of course, this needs some improvement since the function getRemoteIP sets a  constant and maybe the full IP is needed later...

**Comment by slackero** [comment]
Makes sense, but anonymise should be used when saving or displaying the IP only. It should be untouched internally.
