### ISSUE TITLE
Verwendung von Bootstrap Carousel gibt Warning aus

### ISSUE THREAD

**Issue by uwe367** [slackero/phpwcms#239]
Verwende ich im CP **Bilder div** das Template **Bootstrap Carousel** so werden 3 mal die gleichen Warnings ausgegeben:

> Warning: fopen(/www/htdocs/w00xxxx/muster/template/template_lang/de.php): failed to open stream: Permission denied in /www/htdocs/w00xxxx/muster/include/inc_lib/helper.inc.php on line 81

Verzeichnis template/lang hat Chmod 777

Bei der Verwendung eines anderen Templates wird keine Meldung ausgegeben.

phpwcms Version: phpwcms 1.9.0-rc.2 (2018/03/19, r549)
PHP Version: 7.2.1

**Comment by slackero** [comment]
Sieht nach einem Rechteproblem aus, was soll phpwcms da machen, wenn Deine Installation das Schreiben in die Datei nicht zulässt. Prüfe, ob PHP als FastCGI bzw. FPM läuft. Nicht als Apache Modul  nutzen. Checke die Berechtigungen der de.php und unter welchem Nutzer die Datei angelegt wurde. Notfalls löschen. Generiert sich normalerweise selbst neu.

**Comment by uwe367** [comment]
Verzeichnis template_lang hat chmod 777, aber der Hinweis die de.php zu löschen war richitg. Vor dem Löschen lag nur diese in dem Verzeichnis, nach dem löschen liegen dort auch viele andere language php Dateien.
Danke :)
