### ISSUE TITLE
Warning im FE bei Wortbegrenzung in Artikelbasis

### ISSUE THREAD

**Issue by uwe367** [slackero/phpwcms#241]
Erstelle ich einen neuen Artikel und trage in max. Anzahl Worte einen Wert ein, so wird im FE eine Warning ausgegeben:

> Warning: sizeof(): Parameter must be an array or an object that implements Countable in /www/htdocs/wxxxxx/muster/include/inc_ext/htmlfilter.php on line 112

Anbei ein Screenshot zum besseren Verständnis
![screen shot 004](https://user-images.githubusercontent.com/2964678/40419675-577fbe96-5e86-11e8-9f76-27e2e43198f9.jpg)

Lasse ich das Feld leer, wird kein Fehler ausgegeben.
Der Fehler tritt nur dann auf, wenn im Editor Text eingegeben ist. Bleibt der Editor leer und ich trage einen Wert ein, keine Fehlermeldung.
Weiterhin spielt es keine Rolle ob ich das Standarttemplate oder ein anderes Template verwende.

 Version phpwcms 1.9.0-rc.2 (2018/03/19, r549)

**Comment by uwe367** [comment]
Ich weiß nicht ob das der Fehler ist, aber folgende Änderung in der general.inc.php läßt die Fehlermeldungen verschwinden und die Funktionalität bleibt erhalten.
Zeile 993 Original: `if($sanitize !== NULL) {`
Zeile 993 verändert: `if($sanitize == NULL) {`
Keine Ahnung ob das der richtige Weg ist, aber mit der veränderten Datei funktionierts erstmal.....

**Comment by uwe367** [comment]
Dachte ich hätte eine Lösung gefunden, jedoch verursacht genau diese dann den gleichen Fehler im BE während der Fehler im FE verschwindet. Ist aber vielleicht ein Anhaltspunkt.
In general.inc.php
Zeile 993 original: `if($sanitize !== NULL) {`
Zeile 993 verändert: `if($sanitize == NULL) {`
Entfernt zwar den Fehler im FE, dafür hat man ihn dann im BE.

**Comment by uwe367** [comment]
Ich habe nun in der htmlfilter.php die Zeilen, die den Fehler verursachen, versuchsweise auskommentiert. Die Funktion, eine maximale Wortanzahl ist nach wie vor gegeben und die Fehlermeldung ist, im FE sowie im BE weg.
Hier die betreffenden Zeilen (112-116)
Bleibt die Frage ob das der richtige Weg ist..

`//if (sizeof($matches{1})){`
`//$count = strlen($matches{1});`
`//$offset += $count;`
`//}`

**Comment by slackero** [comment]
Schau noch mal, ich bekomme keinen Fehler. Habe htmlfilter.php weiter angepasst – etwas outdated.

**Comment by uwe367** [comment]
Ja, das wars. Keine Fehlermeldungen mehr. Verstehe allerdings nicht warum bei dir kein Fehler ausgegeben wird.
Aktuell verwende ich nun, nach dem letzten Fix der den Fehler nicht beseitigte, phpwcms 1.9.1-dev (2018/05/26, r549) 
PHP Version 7.2.1
Hoster ist all-inkl

**Comment by slackero** [comment]
Meinte nach der Anpassung kein Fehler, vorher habe ich nicht probiert. Aber so wie der Code war, erklärt sich die Meldung.

**Comment by uwe367** [comment]
So war das gemeint.
Nein, nach der heutigen Anpassung wird keine Fehlermeldung mehr ausgegeben.
Danke nochmals :)
