### ISSUE TITLE
Nach Update &amp;listpage=Seite in URL

### ISSUE THREAD

**Issue by uwe367** [slackero/phpwcms#242]
Nach einem Update von einer 1.7.7 auf die neueste Version wird, nachdem ich eine interne Unterseite mit Artikelpaginierung aufgerufen habe, an jede weitere interne URL ` &amp;listpage=Seite` angehangen.
Dann sieht eine Url z.B. so aus: `http://example.de/neu/index.php?index&listpage=9`
Wobei sich die 9 in dem Fall auf die Seite 9 der Artikelpaginierung bezieht und dieser Zusatz in der Url bleibt bestehen, selbst wenn ich die Seite mit der Paginierung verlasse und eine "normale" Unterseite aufrufe.
Bei der 1.7.7 besteht dieser Fehler nicht.

**Comment by slackero** [comment]
Schau mal bitte, ob mein Commit f994b538845537aee14867b40cc8f071b1116d39 hilft

**Comment by uwe367** [comment]
Ok, das funktioniert. Die URL´s werden nach dem verlassen einer Seite mit Paginierung wieder normal angezeigt. 
Danke :)
