### ISSUE TITLE
Information Disclosure - Internal Path Disclosure

### ISSUE THREAD

**Issue by 3xpl01tc0d3r** [slackero/phpwcms#243]
Dear Team,

I have found one vulnerability in the PHPWCMS which discloses the internal path of the application where it has been hosted. I have posted a blog and made a public disclosure about the vulnerability bcoz it wasn't fixed for more than 8 months.
Blog Link - https://3xpl01tc0d3r.blogspot.com/2018/06/information-disclosure-internal-path.html

**Comment by slackero** [comment]
Sorry for that long delay for I guess such simple solution as implemented now. I simply avoid triggering the PHP E_USER_ERROR so that the user logout is processed.
