### ISSUE TITLE
Quick questions about use

### ISSUE THREAD

**Issue by kukrik** [slackero/phpwcms#245]
I have not used phpwcms for a long time, I used the last time since 2007. I made a phpwcms website for a friend of the sports club. Now the website is down. This friend asked me to update my website. I know well that your phpwcms were upgraded to the latest version running from PHP 5.6. But I have to test and see what has been added to the new. If everything is clear to me, then I try to move my friend's page to the latest version.

I made a new install on a clean page and checked out. I do not know if the mistake is in me or anything else. I'll take screenshots here and I will describe a bit.

<img width="1280" alt="screen shot 2018-08-07 at 15 27 39" src="https://user-images.githubusercontent.com/2853034/43778402-447982d2-9a5e-11e8-848d-71fa5323202b.png">

If I want to add a content section, such as text and image, I will use the required fields, I would like to save and close it. But it does not close. I must stop. I understand myself that the data did not reach the database. What's the problem?

<img width="1280" alt="screen shot 2018-08-07 at 15 32 08" src="https://user-images.githubusercontent.com/2853034/43777954-fe9c02e0-9a5c-11e8-8ec8-699216945507.png">

Why is not news displayed?

<img width="956" alt="screen shot 2018-08-07 at 15 41 48" src="https://user-images.githubusercontent.com/2853034/43778023-342f49bc-9a5d-11e8-8787-ff24243c1a51.png">

I'm trying to upload pictures and this error message comes up. In fact, the images are uploaded. I just have to reload the browser. What's the problem?

I sincerely hope that you can respond quickly. Thanks in advance!

EDIT: I forgot to mention that there was no error message.

**Comment by marcus-at-localhorst** [comment]
Info to the second image: You are filtering for a content part "News" and not for the news entries itself.
The content part "News" serves as a container for the News section in the left menu. 
Read more about News CP here: https://wiki.phpwcms.org/doku.php/english/phpwcms-system/article/contentparts/news

**Comment by slackero** [comment]
This is no support section, please move over to [support forum](https://forum.phpwcms.org/)
