### ISSUE TITLE
additional tab input fields: 'type' => 'file'

### ISSUE THREAD

**Issue by q23** [slackero/phpwcms#246]
When using Custom Special Fields it seems that type 'file' isnt available for CP Tabs, only for CP Images. Can you please fix this?
https://github.com/slackero/phpwcms/blob/f4bb31ae4075d92debb3a5142981d95ee717e274/include/config/conf.template_default.inc.php#L460

**Comment by slackero** [comment]
Commit e01f664b22fddd8d48e33845aca0907622a686cd should solves this
