### ISSUE TITLE
Proposal for extension for Bootstrap Navigation RT to get a Multilevel Menu

### ISSUE THREAD

**Issue by uwe367** [slackero/phpwcms#247]
Is it possilble to enhance the Bootstrap Navigation RT, f.e `{NAV_LIST_UL:PB....}` with a dropdown submenu to create a Mulitlevel Menu like in this example? It´s full responsive and, most of all, **touch-friendly**.
[Bootstrap Multilevel Menu](https://www.bootply.com/nZaxpxfiXz)
The reason why is that the current RT doesn´t support it or am i wrong? I don´t know where to add the class `dropdown-submenu`
So it would be very nice if this were built in.

**Comment by slackero** [comment]
It should be possible using the classes defined here:

```
    'navlist-sub_ul_true'           => 'dropdown-submenu',
    'navlist-sub_ul'                => 'sub_ul',
    'navlist-sub_no'                => 'sub_no',
    'navlist-sub_first'             => 'sub_first',
    'navlist-sub_last'              => 'sub_last',
    'navlist-sub_parent'            => 'sub_parent',
    'navlist-asub_no'               => 'asub_no',
    'navlist-asub_first'            => 'asub_first',
    'navlist-asub_last'             => 'asub_last',
    'navlist-link-class'            => 'nav-link',
    'navlist-navLevel'              => 'nav-level-',
    'navlist-bs-dropdown'           => 'dropdown',
    'navlist-bs-dropdown-toggle'    => 'dropdown-toggle',
```

**Comment by uwe367** [comment]
Sorry, but it doesn´t work. The class will be not renderd and it´s not to sse in source code if i add like in your example because, in my opinion,  the Bootstrap RT works only with the last second classes are shown in your posted example.
Have a look into front.func.inc.php around line 3113. 
`if($bootstrap) {
                $li_class   = trim($GLOBALS['template_default']['classes']['navlist-bs-dropdown'].' '.$li_class);
                $bs_toggle  = true;`
and around line 3130.
`if($bs_toggle) {
            $li_a_class     = trim($GLOBALS['template_default']['classes']['navlist-bs-dropdown-toggle'].' '.$li_a_class);
            $bs_data_toggle = ' '.$GLOBALS['template_default']['attributes']['navlist-bs-dropdown-data'];
            $bs_caret       = $GLOBALS['template_default']['attributes']['navlist-bs-dropdown-caret'];`
Other classes will be not rendered at this point when i use the RT `{NAV_LIST_UL:PB....}`
Or do you have a working example for better understanding?
