### ISSUE TITLE
DB fails silently in get_cached_image() function

### ISSUE THREAD

**Issue by marcus-at-localhorst** [slackero/phpwcms#252]
At this point:
https://github.com/slackero/phpwcms/blob/9bea1c42c683e0ef76425383c52bb0cecf68a4d0/include/inc_lib/imagick.convert.inc.php#L234

the `$phpwcms` array with the connection data is missing and crashes (silently, because of the @ error suppression `@mysqli_connect($phpwcms["db_host"]...)`

![image](https://user-images.githubusercontent.com/1337223/50538254-d9cd6180-0b6c-11e9-8b6b-0938008b4344.png)

This helped (at least to get rid of the mysql error)
```
function get_cached_image($val=array(), $db_track=true, $return_all_imageinfo=true) {
    global $phpwcms;
}
```

**Comment by slackero** [comment]
Should be solved
