### ISSUE TITLE
ul eine id zuweisen

### ISSUE THREAD

**Issue by uwe367** [slackero/phpwcms#253]
Mittels NAV_LIST_UL: kann ich jedem `<ul>` eine Klasse zuweisen. 
Beispiel RT: `{NAV_LIST_UL:P,0,2,|mainmenu|submenu|act_path,active}`
Hier bekommt das `<ul>` des Hauptmenüs die Klasse **mainmenu**, die `<ul>` der Submenüs bekommen die Klasse **submenu** zugewiesen
Wäre es möglich an dieser Stelle auch eine id anstatt einer Klasse zu vergeben?
So daß ich `<ul class="meine_klasse"` als auch `<ul id="meine_id">` vergeben kann.

Viele Navigationen arbeiten mit ul-id´s und hier wäre es praktisch wenn es diese Möglichkeit gäbe.

**Comment by slackero** [comment]
Die Funktionalität existiert schon immer. `{NAV_LIST_UL:P,0,2,|mainmenu|submenu|act_path,active,navulid}` wird dann zu `<ul id="navulid_0"…>`

**Comment by uwe367** [comment]
Ah ok. Super. Danke .
Mit der JS Lösung tu ich mich etwas schwer, aber ne ID bekomme ich nun.
