### ISSUE TITLE
Problem mit 1.9.5 und Facebook

### ISSUE THREAD

**Issue by dieterbahr** [slackero/phpwcms#255]
Hab derzeit zwei identische PHPWCMS laufen! Version 1.9.0-rc.2 und die aktuelle 1.9.5 !
Selber Datenbankinhalt, völlig identische Einstellungen und Scripte!
D.h. conf.inc.php => gleiche Einstellungen, gleiche Scripte in init & Render, gleiche Einstellungen in conf.template_default.inc.php
nehme ich nun beispielsweise aus den News einen Link aus dem Browser um diesen in FB zu teilen funktioniert die Zuordnung des
in dem Newsartikel als Bild hinterlegten Bildes tadellos! Zuordnung der URL, Kanonischen URL, og:URL OG:Titel sowie die Zuordnung der entsprechenden og:discription 
Aufgerufene URL: http://www.fotografierbahr.de/blog.html ... ng-audi-a6
Kaninische URL: http://www.fotografierbahr.de/blog.html ... ng-audi-a6
LinkVorschau: passendes Bild aus dem News-Artikel
og:url http://www.fotografierbahr.de/blog.html ... ng-audi-a6 
og:title Fahrzeug-shooting Audi A6
og:image http://www.fotografierbahr.de/im/1200x630x1/90.jpg
og:discription Fahrzeug-Shooting auf Lost Place Gelände

Unter 1.9.5 das gleiche Problem wie bereits unter 1.9.2

Aufgerufene URL: http://foto195.fotografierbahr.de/blog. ... ng-audi-a6
Kaninische URL: http://foto195.fotografierbahr.de/blog.html
LinkVorschau: passendes Bild aus dem News-Artikel
og:url http://foto195.fotografierbahr.de/blog.html 
og:title Blog / Aktuelles
og:image http://www.fotografierbahr.de/im/1200x6 ... rwegen.jpg (das ist das Bild des letzten News Eintrages)
og:discription Fotografierbahr ..... (Meta discription aus der Seite) 

Ich kann mir das beim besten willen nicht erklären und wüsste auch nicht wo ich suchen sollte! Es kann def. nichts mit FB zutun haben, da beide
Systeme gleich eingestellt sind. 

Wie gesagt, alle Einstellungen sind völlig identisch

Hab Screenshoots von Facebook Sharing Debug, aber keine Ahnung wie ich die Hier platzieren kann
Für Hilfe wäre ich dankbar, sonst sitze ich in der Version 1.9.0 fest

DANKE

**Comment by dieterbahr** [comment]
Hab derzeit zwei identische PHPWCMS laufen! Version 1.9.0-rc.2 und die aktuelle 1.9.5 !
Selber Datenbankinhalt, völlig identische Einstellungen und Scripte!
D.h. conf.inc.php => gleiche Einstellungen, gleiche Scripte in init & Render, gleiche Einstellungen in conf.template_default.inc.php
nehme ich nun beispielsweise aus den News einen Link aus dem Browser um diesen in FB zu teilen funktioniert die Zuordnung des
in dem Newsartikel als Bild hinterlegten Bildes tadellos! Zuordnung der URL, Kanonischen URL, og:URL OG:Titel sowie die Zuordnung der entsprechenden og:discription 
Aufgerufene URL: http://www.fotografierbahr.de/blog.html ... ng-audi-a6
Kaninische URL: http://www.fotografierbahr.de/blog.html ... ng-audi-a6
LinkVorschau: passendes Bild aus dem News-Artikel
og:url http://www.fotografierbahr.de/blog.html ... ng-audi-a6 
og:title Fahrzeug-shooting Audi A6
og:image http://www.fotografierbahr.de/im/1200x630x1/90.jpg
og:discription Fahrzeug-Shooting auf Lost Place Gelände


Unter 1.9.5 das gleiche Problem wie bereits unter 1.9.2

Aufgerufene URL: http://foto195.fotografierbahr.de/blog. ... ng-audi-a6
Kaninische URL: http://foto195.fotografierbahr.de/blog.html
LinkVorschau: passendes Bild aus dem News-Artikel
og:url http://foto195.fotografierbahr.de/blog.html 
og:title Blog / Aktuelles
og:image http://www.fotografierbahr.de/im/1200x6 ... rwegen.jpg (das ist das Bild des letzten News Eintrages)
og:discription Fotografierbahr ..... (Meta discription aus der Seite) 

Ich kann mir das beim besten willen nicht erklären und wüsste auch nicht wo ich suchen sollte! Es kann def. nichts mit FB zutun haben, da beide
Systeme gleich eingestellt sind. 

Wie gesagt, alle Einstellungen sind völlig identisch

Hab Screenshoots von Facebook Sharing Debug, aber keine Ahnung wie ich die Hier platzieren kann
Für Hilfe wäre ich dankbar, sonst sitze ich in der Version 1.9.0 fest

DANKE

**Comment by slackero** [comment]
Bitte [neueste Release](https://github.com/slackero/phpwcms/compare/v1.9-php7-dev) prüfen und hier speziell auf die Konfiguration achten, die ich **[in diesem Commit](https://github.com/slackero/phpwcms/commit/f60a6d4062e87afb9404d5427a01f9de853eb31b)** neu eingeführt habe

**Comment by dieterbahr** [comment]
Hallo Oliver,


Erst mal vielen Dank das Du dich dessen angenommen hast! Was mir aber nach wie vor ein Rätsel ist, wie ich das in der Conf.inc.php einstellen soll,
Damit das wieder funktioniert. Es liegt wie Du geschrieben hast, an der default.inc.php
Mit der aus der Version 1.9.0 (die ich nach deinem Hinweis zum Test mal genutzt habe) geht alles

Danke, Dieter

**Comment by dieterbahr** [comment]
Erst mal vielen Dank das Du dich dessen angenommen hast! Was mir aber nach wie vor ein Rätsel ist, wie ich das in der Conf.inc.php einstellen soll,
Damit das wieder funktioniert. Es liegt wie Du geschrieben hast, an der default.inc.php
Mit der aus der Version 1.9.0 (die ich nach deinem Hinweis zum Test mal genutzt habe) geht alles

Danke, Dieter

**Comment by dieterbahr** [comment]
Hallo, ich nochmal, ich glaub ich hab es nun, Danke nochmal!


$phpwcms['preserve_getVar'] = array('page','listpage','newsdetail','newspage','gallery','subgallery');

**Comment by slackero** [comment]
Vermutlich reichen bei Dir `'newsdetail', 'newspage'`
