### ISSUE TITLE
Problem in 1.9.5 files.private.upload.tmpl.php

### ISSUE THREAD

**Issue by hurgelwurz666** [slackero/phpwcms#257]
The following error occurred while trying to upload to image: 
Parse error: syntax error, unexpected '>' in /include/inc_tmpl/files.private.upload.tmpl.php on line 315
After comparing with the last working version, I suspect that the quotation marks in lines 297, 309, 315 and 321 are set incorrectly.

**Comment by slackero** [comment]
Thanks, done
