### ISSUE TITLE
Warning bei MySQLi Abfrage im Setup

### ISSUE THREAD

**Issue by uwe367** [slackero/phpwcms#260]
Bei der MySQLi Abfrage im Setup wird eine Warning, wie im Screenshot gezeigt, ausgegeben. Setup läuft zwar einwandfrei und fehlerfrei durch, aber ich poste das trotzdem mal.
Installation läuft unter XAMPP PHP 7.3.1. und auf dem Server unter PHP 7.2.13.

![screen shot 005](https://user-images.githubusercontent.com/2964678/52176052-e8cbb300-27ad-11e9-89ea-9e5f3dc0960b.jpg)

**Comment by slackero** [comment]
Jo, schon gesehen.
