### ISSUE TITLE
Fehler bei Datei Mehrfachupload phpwcms 1.9.7-rc.1

### ISSUE THREAD

**Issue by uwe367** [slackero/phpwcms#261]
Möchte ich beispielsweise 3 Bilder mittels Datei Mehrfachupload hochladen, so erhalte ich die Meldung daß das speichern der Daten fehlgeschlagen ist. Klicke ich dann nochmals auf Mehrfach Dateiupload, so sind die zuvor ausgewählten Dateien enthalten und können übernommen werden.

**Comment by slackero** [comment]
Kann ich nicht nachvollziehen. Läuft bei mir. Eventuell eine Limitierung Deiner Servereinstellungen.

**Comment by uwe367** [comment]
Ok, Danke für den Hinweis.
Gerade mit einer Installation auf dem Liveserver getestet und dort gibts keine Fehler.
Issue somit erledigt.
