### ISSUE TITLE
Problem mit "Force everything to www. and keep or force SSL status too" in htaccess PHPWCMS 1.9.6

### ISSUE THREAD

**Issue by hurgelwurz666** [slackero/phpwcms#262]
Wenn ich diesen Abschnitt auskommentiere wird anschließend die URL mit zweimal www. generiert:
```
    # Force everything to www. and keep or force SSL status too
    # RewriteCond %{HTTP_HOST} !^$
    # RewriteCond %{HTTPS} off [OR]
    # RewriteCond %{HTTP_HOST} !^www\. [NC]
    # RewriteCond %{HTTPS}s ^on(s)|
    # RewriteRule ^ http%1://www.%{HTTP_HOST}%{REQUEST_URI} [R=301,L]
    # RewriteRule ^(.*)$ https://www.%{HTTP_HOST}%{REQUEST_URI} [R=301,L]
```
Also wenn ich 
MEINE-URL/themen.html
eingebe, wird umgeschrieben in:
https://www.www.MEINE-URL/themen.html

Ich habe die .htaccess wie folgt angepasst um www und ssl zu erzwingen:
```
     RewriteCond %{HTTP_HOST} !^$
     RewriteCond %{HTTP_HOST} !^www\. [NC]
     RewriteCond %{HTTPS}s ^on(s)|
     RewriteRule ^ http%1://www.%{HTTP_HOST}%{REQUEST_URI} [R=301,L]
     RewriteCond %{SERVER_PORT} !=443
     RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]
```
So hat es dann funktioniert.

**Comment by slackero** [comment]
Ja, man sollte an der Stelle wissen, was man tut, deswegen ist das auch auskommentiert. Danke für die Hinweise. Muss ich mal noch klarer herausarbeiten bzw. kommentieren. Teils eine Sammlung
