### ISSUE TITLE
Tabs sorting bricks if more than 4 tabs present

### ISSUE THREAD

**Issue by q23** [slackero/phpwcms#267]
Hi Oli,

if you have more than 4 tabs in a tabs content part the sorting in the backend for the tabs below the first 4 stops working. 

Message when you click on the sorting symbol below the 4th element  in the browser console:
```Uncaught TypeError: Cannot read property 'getPosition' of undefined
    at d.start (mootools-1.1-yc.js:formatted:3318)
    at a (mootools-1.1-yc.js:formatted:469)
    at HTMLElement.<anonymous> (mootools-1.1-yc.js:formatted:484)
```

https://github.com/slackero/phpwcms/blob/master/include/inc_tmpl/content/cnt32.inc.php#L375

Hopefully you could look into it and find the problem soon.

best wishes
q23

**Comment by slackero** [comment]
It works for me as expected. Check if commit fc310cdfee650ead0ab6ecbf31f45ced69fcdd14 solves this. I have not tested yet.

**Comment by q23** [comment]
Thanks, fixes the issue for us.

**Comment by q23** [comment]
The fix does not work if you have a file field present in tabs sorting. I checkt the DOM for the Image output of the tabs in backend, it is valid html with working ids. Maybe the tr > table bricks it somehow?

**Comment by slackero** [comment]
@q23 can you send me a sample with the related config and template files so I can check myself.

**Comment by q23** [comment]
we can provide you ftp and be access as soon as you find the time to check it.

**Comment by slackero** [comment]
You have my email. I will check locally.

**Comment by q23** [comment]
mail done

**Comment by slackero** [comment]
Should be fixed, also on sample website.

**Comment by q23** [comment]
works for us. Thanks!
