### ISSUE TITLE
Notice bei interner Verlinkung (Anker)

### ISSUE THREAD

**Issue by uwe367** [slackero/phpwcms#272]
Ich habe in einem Artikel (Artikelbasis) mehrere Links zu  Contentparts "Dateiliste", in denen jeweils mehrere PDF Dateien abgelegt sind so daß bei einem Klick auf den jeweiligen Link die Dateien angezeigt werden sollen und diese wiederum können mit einem Klick geöffnet werden. 

Die CP`s Dateiliste liegen in eigenen Ebenen, so daß ich mittels Anker darauf zugreifen kann. Heißt daß ich bei einem Klick in eine andere Strukturebene auf den entsprechenden CP springe.
Verlinkung sieht beispielhaft so aus:
index.php?meinLink#cpid187
Im CP ist die Checkbox "Anker" aktiviert.

Allerdings wird mir dabei eine Notice ausgegeben:
Notice: Undefined offset: 1 in D:\xampp\htdocs\mysite\include\inc_front\content\cnt7.article.inc.php on line 62

Insgesamt befinden sich 12 PDF Dateien in dem CP, es werden 11 Noticemeldungen ausgegeben wobei sich die Zahl nach offset: um jeweils +1 erhöht. Also:

Notice: Undefined offset: 1 in D:\xampp\htdocs\mysite\include\inc_front\content\cnt7.article.inc.php on line 62
Notice: Undefined offset: 2 in D:\xampp\htdocs\mysite\include\inc_front\content\cnt7.article.inc.php on line 62
Notice: Undefined offset: 3 in D:\xampp\htdocs\mysite\include\inc_front\content\cnt7.article.inc.php on line 62
Notice: Undefined offset: 4 in D:\xampp\htdocs\mysite\include\inc_front\content\cnt7.article.inc.php on line 62

Version: phpwcms 1.9.10-dev (2019/05/17, r550)

**Comment by slackero** [comment]
Versuche mal bitte, ob meine Änderung hilft

**Comment by uwe367** [comment]
Ja, vielen Dank.
Problem ist gelöst.
