### ISSUE TITLE
upgrade.php Parse error

### ISSUE THREAD

**Issue by DanSchell** [slackero/phpwcms#273]
The upgrade.php shows an syntax error.
Parse error: syntax error, unexpected ')' in xxx\setup\upgrade.php on line 241

if(empty($phpwcms['db_charset']) || empty($phpwcms['db_collation']))) {

I removed one closing bracket and then it worked:
if(empty($phpwcms['db_charset']) || empty($phpwcms['db_collation'])) {

**Comment by slackero** [comment]
Same as issue #269
