### ISSUE TITLE
Exclude CKEditor from Repo

### ISSUE THREAD

**Issue by marcus-at-localhost** [slackero/phpwcms#276]
I would like to see CKEditor loaded from a CDN by default (https://cdn.ckeditor.com/) and gone from the source. I think the CMS shouldn't be responsible for updating a third party lib. And maybe, at some point phpwcms will work with composer, so that php libs can stay out of the repo too. But that's just my personal preference :).
Thanks for keep the updates coming!

**Comment by slackero** [comment]
Sure, but that's a bigger thing – switch to `package.json` or `composer.json`. I have this in mind to handle dependencies the modern way. If I find time I might check how it is solved using https://cdn.ckeditor.com/.

**Comment by slackero** [comment]
I have checked, it makes no sense to switch to the CDN of CKEditor. The CKEditor cannot be replaced the easy way because of dependent functionalities of phpwcms like file upload/management and so on.
