### ISSUE TITLE
Deprecated: __autoload() is deprecated, use spl_autoload_register() instead in

### ISSUE THREAD

**Issue by topixel** [slackero/phpwcms#277]
Ich erhalte folgende Warnung beim Versenden von E-Mails über das Kontaktformular mit PHP 7.2 und 7.3:

Deprecated: __autoload() is deprecated, use spl_autoload_register() instead in /bla/bla/bla/include/inc_ext/phpmailer/PHPMailerAutoload.php on line 45

Ist bei mir zwar noch die Version 1.9.10 - die bemängelte Datei hat sich aber seit 4 Jahren nicht geändert.

**Comment by slackero** [comment]
Scheit ein Problem mit PHP im allgemeinen zu sein, denn der Versionsvergleich der if-Bedingung passt zu PHP >= 5.1.2 >= 5.3.0. Habe schlicht den deprecated Teil entfernt, da grundsätzlich PHP >= 5.5 sein sollte.
