### ISSUE TITLE
Ein paar Fehler unter XAMPP mit PHP 7.3.9

### ISSUE THREAD

**Issue by uwe367** [slackero/phpwcms#278]
Bei der Installation von der neuesten Version wird beim befüllen der DB ein Fehler, wie im Screenshot gezeigt, ausgegeben.
Version phpwcms 1.9.11 (2019/09/20, r550).

![Screen Shot 011](https://user-images.githubusercontent.com/2964678/66392564-86782180-e9d0-11e9-818e-68e4a5288333.jpg)

Beim manuellen einfügen in die DB wird folgende Meldung ausgegeben:
![Screen Shot 013](https://user-images.githubusercontent.com/2964678/66392431-27b2a800-e9d0-11e9-83d7-cb612566ffeb.JPG)

Die Installation kann fortgesetzt werden, jedoch ergeben sich im BE neue Fehlermeldungen wie gezeigt:
![Screen Shot 012](https://user-images.githubusercontent.com/2964678/66392513-57fa4680-e9d0-11e9-8c02-5983cd149150.JPG)

**Comment by uwe367** [comment]
Ich vermute einen Fehler mit meinem XAMPP. Auf dem Live Server läuft die Installation problemlos durch.

**Comment by uwe367** [comment]
Ich muß dieses Issue leider wieder öffnen.
Ich habe weitere Tests durchgeführt und dieses Verhalten taucht auf, sobald PHP 7.3.9 ins Spiel kommt. (Neueste XAMPP Version)
Versuchsweise habe ich eine ältere Version XAMPP mit PHP 7.3.1 installiert und damit gibt es keine Probleme, Installation läuft problemlos durch.
Auf dem Server läuft PHP Version 7.3.6-nmm1 und damit gibt es ebenfalls keine Probleme.

**Comment by slackero** [comment]
Es ist ein MySQL Konfigurationsproblem und eine Änderung in der neueren Release, habe da auf die Schnelle keine Lösung. Siehe https://stackoverflow.com/questions/35565128/mysql-incorrect-datetime-value-0000-00-00-000000.

Identisch mit Issue #275
