### ISSUE TITLE
Fehlermeldungen im CP Formular phpwcms 1.9.11 (2019/09/20, r550)

### ISSUE THREAD

**Issue by uwe367** [slackero/phpwcms#279]
phpwcms 1.9.11 (2019/09/20, r550) PHP 7.3.1
Erstelle ich das erste Formularfeld und bestätige dies indem ich auf "Aktualisieren" klicke, bekomme ich folgende Fehlermeldungen angezeigt:
![Screen Shot 015](https://user-images.githubusercontent.com/2964678/66481208-a70fac80-eaa0-11e9-8b31-0c10482da80e.JPG)

Ich kann dann weiter arbeiten und weitere Formularfelder erstellen. Die Meldung wird im weiteren Verlauf nicht mehr gezeigt.

**Comment by slackero** [comment]
Ist ein Problem in PHP 7.3, in der Produktivumgebung bitte die Warnungen nicht anzeigen.
