### ISSUE TITLE
Checkbox wird nach Formularfehler nicht übertragen

### ISSUE THREAD

**Issue by uwe367** [slackero/phpwcms#280]
Ich habe ein Formular bestehend aus mehreren Einzeltextfeldern, einem mehrzeiligen Textfeld, 4 Checkboxen sowie einem Math Spamschutz. 
Fülle ich alle Felder entsprechend richtig aus, so werden **ALLE** Daten, auch die angehakten Checkboxen, korrekt übertragen.
Provoziere ich nun zum testen einen Fehler indem ich das Ergebnis der Rechenaufgabe falsch eingebe, so werden die Daten nicht versandt und ich kann eine Korrektur vornehmen. ALLE eingetragenen Daten sind im Formular erhalten geblieben, auch die Haken bei den Checkboxen sind nach wie vor gesetzt. Nun trage ich das richtige Ergebnis der Rechenaufgabe ein und die Daten werden versendet.

Und hier kommt der Fehler.
Die Daten aus den Textfeldern werden übertragen, die Daten der Checkboxen nicht obwohl diese angehakt waren. Sieht aus als würde der Inhalt der Checkboxen in der Session verloren gehen....

**Comment by slackero** [comment]
Schwer zu sagen, bitte Link bereitstellen. Formulardaten haben erst mal nichts mit Sessiondaten zu tun.
