### ISSUE TITLE
form class ist nicht anpassbar

### ISSUE THREAD

**Issue by uwe367** [slackero/phpwcms#281]
Ich möchte die Bootstrap Fromvaldierung einbauen wie hier beschrieben.
https://getbootstrap.com/docs/4.3/components/forms/#validation

Dazu ist es aber erforderlich daß ich `form class` selbst definieren kann da
 `<form class="needs-validation" novalidate>` sein muß.
Baue ich die Klasse wie im Screenshot gezeigt ein...
![Screen Shot 017](https://user-images.githubusercontent.com/2964678/66541332-3a8fbe80-eb2f-11e9-9249-ee5b6d85a38e.JPG)
so wird im Quellcode folgendes gerendert:
`<a id="jumpForm4"></a><div class="needs-validation"><form id="phpwcmsForm4" class="form-needs-validation" action="http://localhost/test/#jumpForm4" method="post">`
Und das kann nicht funktionieren da zum einen ein **div** mit dieser Klasse erstellt wird und `form class`  zu `class="form-needs-validation"` . Diese Klasse jedoch existiert nicht.
Weiterhin muß das Attrribut `novalidate` in selbige Zeile eingebaut werden um die browsereigene Validierung deaktivieren. In der derzeitigen Form leider unmöglich da `<form id>` ja bereits automatisch durch das System generiert wird. Ein manuelles einbringen eines weiteren From-Tags wie `<form class="meine-klasse">` hat Fehler zur Folge.

Meine Idee wäre, `form id` und  `form class` in der conf.template_default.inc.php anpassbar zu machen.

Falls es einen anderen Lösungsweg gibt, würde ich mich freuen wenn dieses gezeigt wird.

**Comment by marcus-at-localhost** [comment]
Ich verändere das HTML immer im frontend_render, wenn mir mal was nicht passt.
Dazu kann man entweder PHP DOMDocument nutzen( https://www.php.net/manual/en/class.domdocument.php am Anfang tricky und man muss aufpassen mit HTML in <script> Tags etc) oder der Einfachheit halber phpQuery https://github.com/jae-jae/phpQuery-single (jQuery Syntax[1])

/frontend_render/zzzphpquery.php
```php
/**
 * dom manipulations with phpQuery
 * include_once(TEMPLATE_PATH."inc_script/vendor/phpQuery-onefile.php");
 *
 * @param  string &$html html als reference
 * @return string        result html
 */
function alter_dom(&$html)
{
	$html = phpQuery::newDocument($html);
	
		$html['.form-field input[type=text], .form-field input[type=email], .form-field textarea,.form-field select']->addClass('form-control');
		$html['input:submit']->addClass('btn btn-default btn-lg');

		$html['.form-type-radio-inline label']->addClass('radio-inline');

		foreach($html['.form-type-checkbox span label, .form-checkbox label'] as $input){
			pq($input)->wrap('<div class="checkbox"></div>');
		}
		foreach($html['.form-type-radio label:not(".form-label")'] as $input){
			pq($input)->wrap('<div class="radio"></div>');
		}

		foreach($html[':radio'] as $input){
			pq($input)->parent('label')->wrap('<div class="radio"></div>');
		}

		foreach($html['.form-field [required]'] as $input){
			pq($input)->parents('.form-field')->addClass('required');
		}

		//pq('.required input')->attr('required',true);

		$html['.error']->addClass('has-error');
		$html['.form-field > div > p']->addClass('form-control-static');


	return $html
}

alter_dom($content['all']);
```

Für CP spezifische Manipulation registriere ich eine Funktion in

/frontend_init/phpquery.php

```php
<?php
/**
 * prepare bootstrap form
 * @param string $text html from CP
 * @param array $data CP Data
 */

include_once(TEMPLATE_PATH."inc_script/vendor/phpQuery-onefile.php");

function CP_PHPQUERY($text,  $data) {

	if(! in_array($data['acontent_type'], array(23,0))){
		return $text;
	}

	$html = phpQuery::newDocument($text);

	// Plain text
	if($data['acontent_type'] == 0){
		$html['table']->addClass('table');
	}

	// form
	if($data['acontent_type'] == 23){ // check if this is a form CP
		// honeypot
		$html['form']->append('<input name="hp_url" value="" autocomplete="false"  tabindex="-2">
			<style>[name="hp_url"]{opacity:0;cursor:default;border:none;}</style>');

		$cpdata = unserialize($data['acontent_form']);
		#dd((string) $html, $data, $_REQUEST);

		$search[]	= '/\[label:(.*?)\](.*?)\[\/label\]/s';
		$replace[]	= '<label class="form-label" for="$1">$2</label>';

		$text = preg_replace($search, $replace, $text);


		$html['.form-field']->addClass('form-group form-group-lg');


		// horizontal forms wenn <div form>
		if($cpdata['labelpos'] == 3)
		{
			// create legend
			$html['.form-horizontal .form-field>label']->addClass('col-sm-3 control-label');
			foreach($html['.form-type-breaktext'] as $breaktext){
				$bt = '<legend>'.pq($breaktext)->text().'</legend>';
				pq($breaktext)->replaceWith($bt);
			}
			// wrap input fields
			$wrappers = $html['.form-horizontal .form-field input:submit, .form-horizontal .form-field input[type=text], .form-horizontal .form-field input[type=email], .form-horizontal .form-field textarea, .form-horizontal .form-field select'];
			foreach($wrappers as $input){
				pq($input)->wrap('<div class="col-sm-9"></div>');
			}
			$html['.form-type-submit']->prepend('<label class="col-sm-3"></label>');
		}



		$html['.form-field input[type=text], .form-field input[type=email], .form-field textarea,.form-field select']->addClass('form-control');
		$html['input:submit']->addClass('btn btn-default btn-lg');

		$html['.form-type-radio-inline label']->addClass('radio-inline');

		foreach($html['.form-type-checkbox span label, .form-checkbox label'] as $input){
			pq($input)->wrap('<div class="checkbox"></div>');
		}
		foreach($html['.form-type-radio label:not(".form-label")'] as $input){
			pq($input)->wrap('<div class="radio"></div>');
		}

		foreach($html[':radio'] as $input){
			pq($input)->parent('label')->wrap('<div class="radio"></div>');
		}

		foreach($html['.form-field [required]'] as $input){
			pq($input)->parents('.form-field')->addClass('required');
		}

		//pq('.required input')->attr('required',true);

		$html['.error']->addClass('has-error');
		$html['.form-field > div > p']->addClass('form-control-static');

		// Formular template as file
		$tmpl = PHPWCMS_TEMPLATE.'inc_default/form.html';
		if(file_exists($tmpl)) {
			// load custom template
			$tmpl = file_get_contents($tmpl);
			$html = str_replace('{FORM}',$html, $tmpl);
		}

	}

	return $html;
}

register_cp_trigger('CP_PHPQUERY');
```
Da kann ich die Rohdaten manipulieren, bevor alles in $content['all'] landet.

Ist eine Holzhammermethode, weil je komplexer das ganze wird, desto weniger weiß man bei Fehlern im Frontend ob dieser aus phpwcms kommt oder aus der Dom Manipulation.

Und der Code ist spezifisch für mein Projekt, du musst das anpassen... ist aber relativ einfach und `var_dump` (oder was besseres wie Kint Debugger) ist dein Freund.

[1] man kann die Dom Manipulationen natürlich auch via JavaScript im Frontend vornehmen...

**Comment by uwe367** [comment]
Danke für deine Erklärungen Marcus. Es ist schön wenn man PHP kann. Ich kanns leider nicht. Ich verstehe zwar in etwa was da passiert, aber wirklich weiter komme ich damit nicht. Trotzdem Danke :)

**Comment by slackero** [comment]
Ich werde an der Stelle das Verhalten nicht ändern, das würde zu vielen Problemen bei existierenden Installationen führen.

Benötigst Du eine Ausnahme, dann ist das schnell erledigt, da muss man auch kein DOM lesen und den großen Holzhammer auspacken. Das finale Rendering hat eindeutige Marker, die man dann mit dem Holzhämmerchen bearbeiten kann. In Deinem Fall Frontend Render Ersetzer – nenne Deine Formular-CSS-Klasse z.B. einfach `novalidate`. Dann steht in `<form class="form-novalidate"…>`. Ob die Klasse `form-novalidate` existiert, ist irrelevant. Ersetze nun einfach:
`$content['all] = str_replace('form-novalidate"', 'needs-validation" novalidate');`

**Comment by uwe367** [comment]
Danke.
