### ISSUE TITLE
Umlaute im Alias der Strukturebene werden nicht richtig konvertiert

### ISSUE THREAD

**Issue by uwe367** [slackero/phpwcms#282]
phpwcms 1.9.11 (2019/09/20, r550)
Wie die Überschtrift schon sagt werden Umlaute im Alias der Strukturebene nicht richtig konvertiert.
Aus "ü" wird dann "??"
Siehe Screenshot.
![Screen Shot 018](https://user-images.githubusercontent.com/2964678/67159492-a64f0400-f345-11e9-8f9c-21688e6b296a.JPG)

Ich kenne es vom System so, daß es Umlaute automatisch richtig konvertiert.

**Comment by slackero** [comment]
Prüfe Deine Konfiguration. Ich kann das hier nicht nachvollziehen. Du nutzt sicher eine Mischung aus Latin1-Datenbank mit UTF-8 Charset.

Welche PHP-Version, welcher Browser usw.

**Comment by uwe367** [comment]
Es ist schon merkwürdig. Das Problem taucht nur auf dem Localhost auf, nicht aber auf dem Liveserver.
Trotzdem Danke.
