### ISSUE TITLE
Fehlermeldung beim Löschen einer Strukturebene

### ISSUE THREAD

**Issue by uwe367** [slackero/phpwcms#284]
Wenn ich eine Strukturebene löschen möchte, der eine oder mehrere Ebenen untergeordnet sind, so erhalte ich folgende Fehlermeldung:

> Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 80 bytes) in /www/htdocs/xxxxxx/neu/include/inc_lib/dbcon.inc.php on line 148 

Lösche ich zuerst die untergeordneten Ebenen und dann die Elternebene, ist alles ok.
Provider ist all-inkl. 
phpwcms 1.9.11 (2019/09/20, r550)

**Comment by q23** [comment]
- Reichen wohl 128 MB nicht aus
- Welches PHP konkret (Bezeichnung aus phpinfo kopieren)?

**Comment by slackero** [comment]
Ja, da hast Du wohl wirklich unglaublich viel  Inhalt in den Unterebenen, da hilft nur mehr Speicher.

Prüfe, ob der Account eventuell noch nicht unter PHP CGI/FPM läuft. Falls nicht bereits erfolgt, auf PHP Version 7.3 umstellen.

Und ja, das schrittweise Löschen von unten nach oben ist dann tatsächlich die einzige sinnvolle Lösung. Kann ich mir mal anschauen, sehe aber keine Dringlichkeit.

**Comment by uwe367** [comment]
Da auf dem gleichen Account noch eine Installation unter PHP 5.6 läuft die nicht PHP 7 fähig ist, lade ich PHP 7.3 mittels AddHandler für das entsprechende Unterverzeichnis. PHP Version ist 7.3.11-nmm1. Der Fehler kommt jedoch auch unter PHP 5.6.
Beide Ebenen sind LEER. Weder die Parent noch die Child Ebene enthalten Inhalt.
Zum Testen habe ich lediglich eine Parent und eine Child Ebene angelegt, mehr nicht.
+Parent
++Child
Versuche ich die Parent mit enthaltener Child zu löschen kommt es zu dem Fehler.

**Comment by slackero** [comment]
OK, kann ich nachvollziehen, Fehler ist:
`Uncaught Error: Maximum function nesting level of '256' reached, aborting!`

**Comment by uwe367** [comment]
Funktioniert nun bestens. Danke fürs schnelle erledigen.
