### ISSUE TITLE
wysiwyg - bin mir nicht ganz sicher

### ISSUE THREAD

**Issue by dieterbahr** [slackero/phpwcms#285]
Hallo,
und zwar habe ich festgestellt, das in der Version 1.9.12 ein template aus dem Ordner
inc_cntpart/wysiwyg immer geladen wird, obwohl ich es in keinem Artikel nutze, obwohl es nicht
wysiwyg.tmpl sonder wysiwyg_test.tmpl heißt. 
Aufgefallen ist es mir nur, weil ich zu testzwecken in den tmpl css über " lade

**Comment by q23** [comment]
aber du bist dir nicht ganz sicher?
konntest du es den reproduzieren?
was heißt 'über '' lade'?

**Comment by dieterbahr** [comment]
Kannst schließen, ich bekomm es nicht mehr reproduziert. 
Ich hatte da irgendwas in meiner Testseite und stellte fest, das das aus einen wysiwyg_test.tmpl
kam. Hab aber keinen Plan wie das passiert sein kann. Hab die datei umbenannt und weg war es.
Jetzt bekomm ich es nicht mehr hin. Danke trotzdem
