### ISSUE TITLE
Code Injection Vulnerability can Getshell

### ISSUE THREAD

**Issue by c0d1007** [slackero/phpwcms#286]
## Test version

VERSION 1.9.13, RELEASE 2020/01/10

### setup.php code
Open the secure boot file setup.php,the file path is ```/phpwcms/setup/setup.php```.Then it 
include ```/phpwcms/setup/inc/setup.check.inc.php``` in line 24.

![image](https://user-images.githubusercontent.com/43197505/72501209-39c6a100-3871-11ea-9e34-7bd438750616.png)

### setup.check.inc.php code

 open file ```/phpwcms/setup/inc/setup.check.inc.php``` and you can see line 35.

![image](https://user-images.githubusercontent.com/43197505/72501380-932ed000-3871-11ea-8911-0fcfbd9b4b28.png)

### setup.func.inc.php code

tarck the function write_conf_file() in ```/phpwcms/setup/inc/setup.func.inc.php``` in line 119.

![image](https://user-images.githubusercontent.com/43197505/72501497-ee60c280-3871-11ea-9ae2-fdda335c02f1.png)

and in line 293,it will call function write_textfile() to write the config file in line 35.

![image](https://user-images.githubusercontent.com/43197505/72501526-fc164800-3871-11ea-8a09-7ba40c1f02a6.png)

![image](https://user-images.githubusercontent.com/43197505/72501564-1ea86100-3872-11ea-8612-b98908a1c859.png)

## Testing getshell

in this interface,you can input some infomation like this.

![image](https://user-images.githubusercontent.com/43197505/72501648-53b4b380-3872-11ea-900f-653173da24f0.png)

### payload

```
root';phpinfo();$test='a
```

After completing it, click Submit.It will show some error information,but you can access like this address and you can see it run the injection code.

![image](https://user-images.githubusercontent.com/43197505/72501769-af7f3c80-3872-11ea-880e-8b9c2448d80f.png)

## Solution

Filtering some sensitive characters.

**Comment by slackero** [comment]
Thanks, patch should solve the problem.
