### ISSUE TITLE
Form CP and GDPR default Setting after Update

### ISSUE THREAD

**Issue by marcus-at-localhost** [slackero/phpwcms#289]
I just had a case where an updated phpwcms instance couldn't send emails from CP form anymore. There was no error on the frontend or backend. Everything looked fine.

After taking a closer look at the CP Form, I noticed, that **aktiviere Double Opt-In gemäß der Datenschutzgrundverordnung (DSGVO)** was activated and the following forms were empty. After deactivating the Double Opt-In, everything worked fine.

It's possible to make sure, that user know about this feature and be warned or something? Or to not activate it at all?

Thanks

**Comment by slackero** [comment]
I need to check. Was mostly merged from [q23](https://github.com/q23/phpwcms/tree/double-opt-in) and I never found time to test it intensively.

**Comment by q23** [comment]
We use it a lot, and also some new project with deactivated Double Opt-In. So i'm pretty sure it works as excepted
Solution for this case could be a fallback text if feature is activated but field is empty would solve the problem
