### ISSUE TITLE
Warnung bei Installation Version 1.9.13

### ISSUE THREAD

**Issue by uwe367** [slackero/phpwcms#290]
Bei der Installation phpwcms 1.9.13 wird eine Warnung wie im Screenshot gezeigt ausgegeben:
![Screen Shot](https://user-images.githubusercontent.com/2964678/75095877-c1eb4500-5599-11ea-9e01-2305d851aad8.JPG)

Bei der Version 1.9.14 wird diese Warnung nicht ausgegeben:
![Screen Shot 001](https://user-images.githubusercontent.com/2964678/75095889-df201380-5599-11ea-9cbb-bea3fcfd77eb.JPG)

Identische Installationsbedingungen unter XAMPP.

**Comment by slackero** [comment]
Deswegen gibt es ja die neuere Version
