### ISSUE TITLE
Notice Artikelübersicht Version 1.9.14 PHP Version 7.4.2

### ISSUE THREAD

**Issue by uwe367** [slackero/phpwcms#291]
In der Version 1.9.14 unter PHP 7.4.2 erscheint folgende Notice wenn man den ersten Artikel erstellen möchte:
![Screen Shot 002](https://user-images.githubusercontent.com/2964678/75109832-a169cc00-5627-11ea-8ab7-53205209fa00.JPG)
Nachdem der erste Artikel erstellt wurde erscheint die Meldung nicht mehr.

**Comment by slackero** [comment]
Sollte gefixt sein
