### ISSUE TITLE
Bearbeitungsdatum anderer CP´s ändert sich wenn ein CP verschoben wird

### ISSUE THREAD

**Issue by uwe367** [slackero/phpwcms#295]
Verschiebe ich einen Content Part innerhalb eines Artikelbaumes, so ändert sich das Bearbeitungsdatum aller CP`s, über die der neue CP mittels der Pfeilbuttons verschoben wird. Feature oder Bug?
Ich würde eher Bug sagen da die Inhalte der CP´s selbst nicht bearbeitet, sondern nur nach unten bzw, nach oben verschoben werden.
Zum besseren Verstänids hier Screenshots. Man beachte das Datum der CP´s.
![CP1](https://user-images.githubusercontent.com/2964678/77510422-0e62c280-6e6f-11ea-920d-292df2e8a62a.jpg)

Screenshot CP 2 zeigt den CP mit der ID 7, der nach oben verschoben wurde und somit bei den  CP`s ID 3 und 6 automatisch nur durch das Verschieben innerhalb des Artikelbaumes das Datum geändert wird.
![CP2](https://user-images.githubusercontent.com/2964678/77510551-597cd580-6e6f-11ea-90ef-813fc59d2734.jpg)

Betrifft neueste sowie auch ältere phpwcms Versionen.

**Comment by jensensen** [comment]
Kann ich bestätigen. Allerdings auch dann, wenn ich einen CP z. B. in einer
-> section ändere.
Dann haben die anderen CP das gleiche neue Änderungsdatum.
Das sollte so nicht sein.

Uwe Tholey <notifications@github.com> schrieb am Mi., 25. März 2020, 08:08:

**Comment by slackero** [comment]
Das war schon immer so

**Comment by uwe367** [comment]
> 
> 
> Das war schon immer so

Was nicht heißen muß daß das das richtige Verhalten ist.
Verschiebt man CP´s indem man den Sortierungswert ändert, ändert sich das Datum nicht.

**Comment by jensensen** [comment]
Wenn man 1 CP bearbeitet,  will man doch nicht, dass sich das
Änderungsdatum aller anderen CPs ebenfalls ändern.
Das war bislang auch nicht so.

Uwe Tholey <notifications@github.com> schrieb am Do., 26. März 2020, 06:03:

**Comment by uwe367** [comment]
Bearbeiten bitte nicht mit Verschieben verwechseln. Unter Bearbeiten verstehe ich daß der Inhalt eines CP verändert wird. Das funktioniert ja auch ohne daß sich das Datum der anderen CP´s ändert. Es tritt lediglich auf wenn ich CP x "über" andere nach oben oder nach unten schiebe.

**Comment by jensensen** [comment]
Bei mir ändert sich das Datum aller CP, wenn ich nur einen bearbeitet habe.
Nicht nur beim verschieben.

Oliver Georgi <notifications@github.com> schrieb am Do., 26. März 2020,
10:28:

**Comment by uwe367** [comment]
> 
> Bei mir ändert sich das Datum aller CP, wenn ich nur einen bearbeitet habe. Nicht nur beim verschieben.

Kann ich nicht bestätigen. Bei mir klappt es nun wie es soll.
Mit Olivers Fix kann ich die CP´s verschieben ohne daß sich das Datum ändert und wenn ich einen CP bearbeite (Inhalt ändere) wird auch nur bei diesem das Datum geändert.

Danke fürs schnelle Bearbeiten Oliver.

**Comment by slackero** [comment]
> Bei mir ändert sich das Datum aller CP, wenn ich nur einen bearbeitet habe. Nicht nur beim verschieben.

Kannst Du mal beschreiben, wie Du vorgehst?
