### ISSUE TITLE
Fehler in article_summary.tmpl bei verlinkten Bildern

### ISSUE THREAD

**Issue by topixel** [slackero/phpwcms#297]
Hi, 
noch nie gebraucht, aber eben über folgenden Fehler gestolpert: 

Verpasse ich dem Artikel-Bild in der Bildbeschreibung ein Link-Ziel, verschluckt sich die HTML-Ausgabe mit einem doppelten <a href=... . Ergänze ich noch ein _blank, wird es noch schlimmer.

Packe ich z. B. folgendes in die Bildbeschreibung:
`Bildunterzeile | altAttr. | LinkZiel _blank | titleAttr. | Copyright`

erhalte ich folgenden HTML-Code:

```
        <div class="article-summary-image">
        <a href="LinkZiel" target=" target="_blank"">
            <a href="LinkZiel" target="_blank" class="image-link"><img src="content/images/41715c158ce18d2c82e9ddd43482d6ce.jpg" width="490" height="294" alt="altAttr." title="titleAttr." class="image-article-summary"></a><span class="caption">
                Bildunterzeile
                <span class="copyright">Copyright</span>
            </span>
        </a>
        </div>
```
Wenn ich in /template/inc_default/article_summary.tmpl Zeile 6 und 11 lösche, dann ist alles gut. 

(Eventuell betrifft das auch nebenan die article_summary_list.tmpl - das habe ich noch nicht getestet.)

Grüße,
top

**Comment by slackero** [comment]
Ja doppelt gemoppelt, ich habe es im Template separiert und das `target` Attribut gefixt. Das ist eigentlich für den Fall, wenn man sich das Bild mit custom Tag umsetzt.
