### ISSUE TITLE
PDF Linkziel funktioniert nicht richtig (R 1.9.15/18)

### ISSUE THREAD

**Issue by Huong-II** [slackero/phpwcms#298]
Die Beschreibung unter dem CP Dateiliste für (PDF-)Blockfenster sieht wie folgt aus:

>  Beschreibung | Dateiname | Dateititel | Link Ziel | BxHxC (wenn Bild) | Copyright ↵ … 

Mit der Konfiguration wie Beschreibung | | | _blank funktioniert es nicht, es wird kein weiteres Fenster für die PDF geöffnet.

**Comment by slackero** [comment]
Sollte gefixt sein. Der Knackpunkt war, dass ich das im Standardtemplate an die Bedingung geknüpft hatte, dass `{FILE_TARGET}` nur für den Fall gerendert wurde, dass auch ein Link zusammen mit dem Ziel gesetzt war. Diese bedingung habe ich in den Standardvorlagen entfernt.

Parallel wurde eine weitere Template-Option `inline_download` eingeführt, die das globale Setting `$phpwcms['inline_download']` überschreibt.
