### ISSUE TITLE
Bootstrap Navigation - active class for navigation links

### ISSUE THREAD

**Issue by santscho** [slackero/phpwcms#299]
Hello Oliver. It would be great to have the active-class within the `<a>` attribute to make the standard Bootstrap Navigation Pills working (pill background with the rounded corners). Currently, only the `<li>` element gets the active class.
 
in conf.template_default.inc.php something like
`'navlist-bs-link-active'               => 'active',`

```
<ul class="nav nav-pills">
    <li class="nav-item"><a class="nav-link active" href="#">First Item</a></li>
    <li class="nav-item"><a class="nav-link" href="#">Second Item</a></li>
    <li class="nav-item"><a class="nav-link" href="#">Third Item</a></li>
</ul>
```

**Comment by slackero** [comment]
Try this and check the source text for the active class results – should work like you expect:
`{NAV_LIST_UL: PB, 0, , active|nav navbar-nav|nav-sub, active_li | active_a}`

Here is the explanation:
```
menu_type,
start_id,
max_level_depth,
class_path|ul_class_level1|ul_class_level2|...,
class_active_li|class_active_a,
ul_id_name,
wrap_ul_div(0 = off, 1 = <div>, 2 = <div id="">, 3 = <div class="navLevel-0">),
wrap_link_text(<em>|</em>),
articlemenu_start_level|articlemenu_list_image_size (WxHxCROP OR WxHxCROP)|_
articlemenu_use_text (take text from: description:MAXLEN OR menutitle:MAXLEN OR teaser:MAXLEN OR teaser:HTML)|_
articlemenu_position (inside|outside)|_
<custom>[TEXT]{TEXT}[/TEXT][IMAGE]<img src="{IMAGE}" alt="{IMAGE_NAME}">[/IMAGE]</custom>
```
