### ISSUE TITLE
PHP 8. In Dateizentrale werden keine Thumbnals generiert, keine Bildauswahl im CP möglich

### ISSUE THREAD

**Issue by uwe367** [slackero/phpwcms#301]
Version: phpwcms 1.9.22-dev (2020/12/10, r551)
Unter PHP 8 werden in der Dateizentrale keine Thumbnails generiert.
![Screen Shot](https://user-images.githubusercontent.com/2964678/102010591-484a6080-3d3f-11eb-96e1-de55162e3d39.jpg)

Im CP "Bilder div" sowie "Bilder spezial" werden keine Dateien zur Auswahl in der Dateizentrale angezeigt obwohl Bilder vorhanden sind.
![Screen Shot 001](https://user-images.githubusercontent.com/2964678/102010619-7e87e000-3d3f-11eb-92af-c88557b9b691.JPG)

Erstelle ich einen CP "Dateiliste", so werden alle Dateien inkl der PDF angezeigt und können ausgewählt werden.
![Screen Shot 002](https://user-images.githubusercontent.com/2964678/102010632-9495a080-3d3f-11eb-9611-e00c0b7d412e.JPG)

**Comment by slackero** [comment]
Es wäre schön, Du würdest mir die Fehlerlogs dazu senden. Also unbedingt error_reporting aktivieren und am besten in ein Fehlerlog schreiben lassen. Dann sehe ich eventuell sofort, wo Anpassungen nötig sind.

**Comment by uwe367** [comment]
Error Reporting ist aktiv, jedoch werden keine Fehler ausgegeben, Weder im BE direkt noch in der php_error_log.
Oder gibt es noch eine andere Möglichkeit den Fehler zu finden?

**Comment by slackero** [comment]
Das siehst Du in der phpinfo im Backend. Es muss Fehler geben, setze in der conf.inc.php noch folgendendes ein:

`error_reporting(E_ALL);`

**Comment by uwe367** [comment]
Ah, ok. Da sind nun Fehler zu sehen und zwar folgende:
Im BE im der Dateizentrale wo die Thumbs fehlen:

**Deprecated: Required parameter $phpwcms follows optional parameter $cutID in D:\xampp\htdocs\test\include\inc_lib\files.private-functions.inc.php on line 14**

Dann noch folgende Meldungen im Frontend sowie im BE sichtbar:
**Deprecated: Required parameter $maxLength follows optional parameter $cutString in D:\xampp\htdocs\test\include\inc_lib\general.inc.php on line 1114**

**Deprecated: Required parameter $sitemap follows optional parameter $start in D:\xampp\htdocs\test\include\inc_front\front.func.inc.php on line 2447**

**Deprecated: Required parameter $sitemap follows optional parameter $counter in D:\xampp\htdocs\test\include\inc_front\front.func.inc.php on line 2495**

**Deprecated: Required parameter $date follows optional parameter $text in D:\xampp\htdocs\test\include\inc_front\front.func.inc.php on line 2581**

**Deprecated: Required parameter $date follows optional parameter $text in D:\xampp\htdocs\test\include\inc_front\front.func.inc.php on line 2602**


Dann, wenn ich die phpinfo aufrufe..
**Deprecated: Required parameter $maxLength follows optional parameter $cutString in D:\xampp\htdocs\test\include\inc_lib\general.inc.php on line 1114**

**Deprecated: Required parameter $file_image_size follows optional parameter $filename in D:\xampp\htdocs\test\include\inc_lib\backend.functions.inc.php on line 130**

**Deprecated: Required parameter $leftData follows optional parameter $id in D:\xampp\htdocs\test\include\inc_lib\backend.functions.inc.php on line 379**

**Deprecated: Required parameter $rightData follows optional parameter $id in D:\xampp\htdocs\test\include\inc_lib\backend.functions.inc.php on line 379**

Rufe ich die Artikelzentrale auf, kommt folgende Meldung hinzu:
**Deprecated: Required parameter $selected_id follows optional parameter $counter in D:\xampp\htdocs\test\include\inc_lib\article.functions.inc.php on line 86**

Bei Bedarf und falls benötigt schicke ich gerne die php error log per Mail zu. Diese enthält nun auch Fehlermeldungen.

**Comment by slackero** [comment]
Is related to issue #302
