### ISSUE TITLE
PHP 8: Neue Seitenebene anlegen nicht möglich (Fehlermeldung)

### ISSUE THREAD

**Issue by uwe367** [slackero/phpwcms#302]
phpwcms 1.9.22-dev (2020/12/10, r551)
Lege ich eine neue Seitenebene an, so erscheint im Browser nur noch eine Fehlermeldung und er Arbeitsbereich ist komplett verschwunden:
**Fatal error: Unparenthesized `a ? b : c ? d : e` is not supported. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in D:\xampp\htdocs\test\include\inc_act\act_structure.php on line 124**

Gegencheck mit PHP 7.4.10 funktioniert problemlos.

**Comment by slackero** [comment]
Du kannst ja mal den Branch [v1.9-php8-dev ](/slackero/phpwcms/tree/v1.9-php8-dev)prüfen

**Comment by uwe367** [comment]
Das Anlegen einer Seitenebene funktioniert nun fehlerfrei, jedoch werden in der Dateizentrale unter PHP 8 nach wie vor keine Thumbnails generiert und auch weiterhin ist eine Bildauswahl im CP, z.B. Bilder div, nicht möglich da keine Bilddateien zur Auswahl angeboten werden (siehe Issue 301).
Unter PHP 7.4.13 klappt alles bestens, selbst der Branch v1.9-php8-dev läuft unter PHP 7.4.13 fehlerfrei.
Aber nun wünsche ich Dir frohe Weihnachten und ein friedvolles Fest, auch wenn das eigentlich nicht hierher gehört.

**Comment by slackero** [comment]
Prüfe bitte, ob die GD Erweiterung überhaupt aktiv ist. Hier funktioniert `gd2`. Oder ob eventuell eine andere Bildverarbeitungs-Methode eingestellt ist, die in Deiner Umgebung nicht zuverlässig arbeitet.

**Comment by uwe367** [comment]
Treffer Oliver. Die GD Erweiterterung war in der ini.php auskommentiert und somit inaktiv. Beim Setup wurde auch angezeigt daß keine GD Erweiterung installiert ist bzw. war. Nach dem aktivieren läufts nun wie es soll.
