### ISSUE TITLE
PNG Dateien werden nicht richtig erkannt

### ISSUE THREAD

**Issue by uwe367** [slackero/phpwcms#306]
phpwcms 1.9.25 (2021/05/22, r551).
PNG´s werden nicht richtig erkannt. In der Dateizentrale werden nur Icons statt Bildvorschau angezeigt und sind im CP (z.B. Bilder div) nicht auswählbar bzw. Verzeichnis wird leer angezeigt.
![Screen Shot 004](https://user-images.githubusercontent.com/2964678/119303128-81c7b600-bc65-11eb-8164-72775c22e174.jpg)

**Comment by gehring-media** [comment]
Version 1.9.24 hat das Problem noch nicht

**Comment by slackero** [comment]
Kann ich nicht nachvollziehen.

**Comment by uwe367** [comment]
Danke. Funktioniert jetzt.
