### ISSUE TITLE
Neue _.htaccess macht Probleme

### ISSUE THREAD

**Issue by topixel** [slackero/phpwcms#308]
Selbst bei einer frischen Installation führen Zugrugriffe auf eine Dateien mit der Endung .html zu einer Fehlermeldung. 
Das betrifft sowohl tatsächlich existierende Dateien, als auch der Zugriff auf "index.html" über den Home-Schalter der Navigation.

Als Workarround nutze ich erst mal noch den Stand der _.htaccess-Datei vom 30. März 2021.

**Comment by slackero** [comment]
Irgendwas geht da wohl quer.

**Comment by slackero** [comment]
Prüfe mal bitte die Änderungen.

**Comment by topixel** [comment]
Vielen Dank, jetzt geht es wieder.
