### ISSUE TITLE
CP Formular, Textfeld läßt sich nur horizontal vergrößern

### ISSUE THREAD

**Issue by uwe367** [slackero/phpwcms#309]
Im CP Formular, Bereich "Wert" läßt sich das Textfeld nur horizontal, aber nicht vertikal vergrößern / verkleinern. Bei mehreren Werten, wie z.B. einer Gruppe bestehend aus Radio Buttons ist auch scrollen innerhalb des Feldes nicht möglich und das Feld passt sich nicht dem Inhalt an. Es bleibt dann nur die Möglichkeit im Feld mit den Pfeiltasten auf und ab zu navigieren.
Anbei ein Screenshot welches Feld gemeint ist.
![Screen Shot](https://user-images.githubusercontent.com/2964678/121642719-3567dd00-ca91-11eb-8e36-0c540ebbe9cc.JPG)

Habe gerade noch festgestellt daß dieses Verhalten nur bei copy & paste auftritt.

Mir ist auch aufgefallen daß dies bei den Feldern im Bereich "Vorlage", also Haupttemplate ebenfalls der Fall ist. Hier passen sich jedoch die Felder dem Inhalt an. Bug oder so gewollt?

**Comment by topixel** [comment]
Gerade mal bei einer frisch aktualisierten Seite ausprobiert. Bei mir lässt sich das ebenfalls manuell nicht in die Höhe ziehen. 

Sobald ich aber auch nur ein Zeichen in dem Feld tippe, (und auch bei "copy & paste") scheint da ein JavaScript zu greifen, welches mir das Feld auf die komplette Höhe des Inhaltes setzt. 

Welchen Browser nutzt du? 

Bzw.: Hast du irgend einen Blocker laufen der das JS in der Funktion behindert?

**Comment by uwe367** [comment]
Danke für deine Hinweise. Ich muss das nochmal testen. Ich nutze Firefox in der neuesten Version und Blocker habe ich keine installiert, weder Browser- noch Systemseitig. Bei copy and paste wird zwar der Inhalt komplett eingefügt, jedoch verändert sich der Eingabebereich nicht in der Größe so daß es nur auf Umwegen möglich ist an den nicht sichtbaren Inhalt zu kommen. Also so wie ich im Eingangspost beschrieb.

**Comment by slackero** [comment]
Hm, ich kann das nicht ganz nachvollziehen. Die Felder werden automatisch in der Höhe angepasst. Dass man dort sehr viel eingibt, kommt eher selten vor. Wenn man an das Ende eines Feldes springt und Return drückt, wird an sich sofort die Höhe angepasst. Das Verhalten ist seit Jahren unverändert.

**Comment by uwe367** [comment]
Hm, ok. Dann ist mir das wohl noch nie aufgefallen weil man dort eben normalerweise nicht sehr viel eingibt und das jetzt das erste Mal war daß dort mehr Inhalt drin steht. Ich schließe das Issue als gelöst da das Verhalten dann normal ist.
