### ISSUE TITLE
Code execution during installation

### ISSUE THREAD

**Issue by AirSkye** [slackero/phpwcms#310]
进入安装流程，在MySQL database settings处输入payload：`root\';phpinfo();//`

Enter the installation process, enter the payload in the MySQL database settings: `root\';phpinfo();//`
![1624353999296](https://user-images.githubusercontent.com/55659004/123062542-34469080-d43f-11eb-83f9-531226346f3d.png)
点击Continue。重新刷新页面，执行php代码

Click Continue. Re-refresh the page and execute the php code
![1624354054503](https://user-images.githubusercontent.com/55659004/123062566-390b4480-d43f-11eb-90d5-ab0b49c37046.png)
在`setup/inc/setup.func.inc.php` 的`write_conf_file`中对外部输入参数进行了过滤并拼接

The external input parameters are filtered and spliced in the `write_conf_file` of `setup/inc/setup.func.inc.php`
![1624354234211](https://user-images.githubusercontent.com/55659004/123062579-3c063500-d43f-11eb-9c65-10a19ca75fac.png)
过滤替换`'`为`\'`，输入`\'`将被替换为`\\'`，前面的`\`将后面的`\`进行了转义导致其失效。

Filtering replaces `'` with `\'`, inputting `\'` will be replaced with `\\'`, the front `\` will escape the following `\` to make it invalid.
![1624354344281](https://user-images.githubusercontent.com/55659004/123062593-3f99bc00-d43f-11eb-8b1a-7f9ea6dd14a9.png)
最终结果

Final Results
![1624354441095](https://user-images.githubusercontent.com/55659004/123062604-4294ac80-d43f-11eb-9ba9-9dded4da1ccb.png)

**Comment by slackero** [comment]
Thanks for reporting this potential problem.
