### ISSUE TITLE
Arbitrary file deletion vulnerability

### ISSUE THREAD

**Issue by AirSkye** [slackero/phpwcms#311]
在`include/inc_act/act_ftptakeover.php` 334行中，传入`unlink`方法的变量`$file`并未做过滤，导致可以使用../这种形式进行目录穿越删除任意文件。
In the 334 line of `include/inc_act/act_ftptakeover.php`, the variable file passed in the `unlink` method is not filtered, so that the form of ../ can be used for directory traversal to delete any `$file`.

![image](https://user-images.githubusercontent.com/55659004/124229219-da7d4f00-db3f-11eb-8928-5415f37e3d64.png)
![image](https://user-images.githubusercontent.com/55659004/124229388-1ca69080-db40-11eb-8fc4-343a37297fb2.png)

漏洞复现：
Vulnerability recurrence:
登录访问后台页面http://www.pw.com/phpwcms.php?csrftoken=0cc175b9c0f1b6a831c399e269772661&do=files&p=8
首先上传文件后，选中第一个文件，点击take over selected files
Login to visit the background page http://www.pw.com/phpwcms.php？csrftoken=0cc175b9c0f1b6a831c399e269772661&do=files&p=8
After uploading files first, select the first file and click take over selected files

![image](https://user-images.githubusercontent.com/55659004/124229703-98084200-db40-11eb-8922-df11b5680f0b.png)

使用burpsuite抓包，修改第一个文件的字段段属性，对内容进行base64解码修改为`../_.htaccess`并再次编码，尝试删除根目录下_.htaccess文件
Use burpsuite to capture packets, modify the field attributes of the first file, base64 decode the content, modify it to` ../_.htaccess` and encode it again, try to delete the _.htaccess file in the root directory

![image](https://user-images.githubusercontent.com/55659004/124233036-00592280-db45-11eb-8224-f677f388bce2.png)
![image](https://user-images.githubusercontent.com/55659004/124233097-123ac580-db45-11eb-9c92-da3e6a34b04b.png)
![image](https://user-images.githubusercontent.com/55659004/124233138-1bc42d80-db45-11eb-8d7b-c56cfcb9fb71.png)

调试查看变量值
Debug to view variable values

![image](https://user-images.githubusercontent.com/55659004/124233161-254d9580-db45-11eb-9ced-36b9f90e28a1.png)

文件被成功删除
The file was successfully deleted

![image](https://user-images.githubusercontent.com/55659004/124229855-ce45c180-db40-11eb-8dd6-324bf8387b2d.png)

修复建议：
1.过滤../等特殊字符。
2.限制目录访问权限。

Repair suggestions:
1. Filter ../ and other special characters.
2. Restrict directory access permissions.

**Comment by slackero** [comment]
So old problems at all, thanks for finding and reporting this. It's rarely a real problem because only editors have access but anyway it shouldn't be possible in any case.
