### ISSUE TITLE
Mehrfach-Dateiupload mag keine SVG

### ISSUE THREAD

**Issue by topixel** [slackero/phpwcms#313]
Versuche ich mehrere SVG-Dateien über den Mehrfach-Dateiupload in die Dateizentrale zu laden, werden diese weder im Backend noch im Frontend angezeigt. 
Die selben SVGs lassen sich aber problemlos einzeln über das kleine Upload-Symbol der Ordner hochladen.

**Comment by slackero** [comment]
Gelöst https://github.com/slackero/phpwcms/commit/0ab933a2d37f397a8fa5da2d31576e30951de00e
