### ISSUE TITLE
phpwcms 1.9.26 throws syntax error on PHP 5.5

### ISSUE THREAD

**Issue by prbt2016** [slackero/phpwcms#315]
Hello,

I was in the process of manual installation of phpwcms 1.9.26 on Centos 6.9 Final with PHP 5.5, MYSQL 5.5, Apache 2.2.34 downloaded from here : 

https://github.com/slackero/phpwcms/archive/v1.9.26.zip

However after successful installation, on accessing the frontend I get the following error i.e : 

` Parse error: syntax error, unexpected '?', expecting ',' or ';' in /{{PATH}}/{{TO}}/{{phpwcms}}/include/inc_lib/helper.image.php on line 41`

On inspecting the code in 'helper.image.php' on line 41 i.e : 

`var $target_ext = PHPWCMS_WEBP ? 'jpg' : 'webp'; ` which is a constant expression and the syntax is supported since PHP 5.6 : 

https://www.php.net/manual/en/migration56.new-features.php

But minimum requirement mentioned is PHP 5.5 here : 

https://github.com/slackero/phpwcms/tree/master#server-system-requirements

Could you please fix this?.

**Comment by prbt2016** [comment]
Hello,

Awaiting your reply on this. Did you check with the above issue on PHP 5.5. Kindly let me know.

Regards.

**Comment by slackero** [comment]
I do not check issues every day, and to be true I do not test intensive against PHP 5.5
