### ISSUE TITLE
base_href läst sich in conf.inc.php nicht abstellen

### ISSUE THREAD

**Issue by topixel** [slackero/phpwcms#316]
Trotz der Einstellung in der conf.inc.php:
`$phpwcms['base_href'] = false; // set the <base href=""> tag, use string (URL) or bool TRUE/FALSE`
wird im Frontend:
`<base href="https://example.com/">`
erzeugt.

Dadurch lassen sich allgemeine Sprunganker nicht mehr auf Unterseiten setzten, da man dadurch immer auf der Startseite landet.

**Comment by slackero** [comment]
Vorsicht damit! Sowie ReWrite an ist, und `<base href>` aus, und man relativ auf z.B. CSS oder Bilder etc. verweist, und man irgendwo z.B. in `meine/segment/whatever` ist, werden Assets nicht mehr geladen. Diese müssen dann immer absolut eingebunden werden `/assets…`
