### ISSUE TITLE
CP Formular, Zeilenumbruch im Feld Wert erzeugt zweite checkbox

### ISSUE THREAD

**Issue by uwe367** [slackero/phpwcms#318]
Version phpwcms 1.9.29-dev (2021/09/01, r552) unter PHP 8.0.8
Erstelle ich im CP Formular eine Checkbox und baue im Feld "Wert" beispielsweise einen Bestätigungstext ein der einen Zeilenumbruch oder ein break, `<br>` oder `<br />`, enthält, so wird im Frotend ab diesem Umbruch oder break eine zusätzliche Checkbox erzeugt.
Läuft der Text ohne Umbruch oder break durch, ist alles in Ordnung.
Festgestellt bei einer brandneuen Installation mit Standarttemplate, keine weiteren Dateien hinzugefügt.
Anbei ein Screenshot zur Verdeutlichung.
Nach dem Wort "gelöscht" habe ich einen einfachen Zeilenumbruch mittels Tastatur eingefügt und damit wird im FE ab dem Wort "Sie" eine weitere Checkbox erzeugt. Gleiches passiert, wie oben beschrieben, durch ein break.
![checkbox2](https://user-images.githubusercontent.com/2964678/132119806-4d62302f-5432-4626-9484-453d85f58477.jpg)

Bug oder liegt der Fehler bei mir?

**Comment by slackero** [comment]
Das ist ein gewolltes Verhalten. Nutze [br] (BBCode) Tags für die Formatierung. 

Ansonsten Empfehlung! Keine solchen Werte für die Checkbox selbst benutzen. Erinnere Dich an die Trennung Label und Wert mittels `-|-`. Das Labekl kannst Du auch über die Sprachersetzer @@MeinLabelWert@@ setzen, siehe nach Rendering in template/template_lang/*.php

**Comment by uwe367** [comment]
Ja, ich erinnere mich an die Trennung, das habe ich im Hinterkopf. Und danke Dir für den Hinweis.
Ich habe vermutet dass das ein gewolltes Verhalten ist und werde es entsprechend umsetzen.
