### ISSUE TITLE
Alias der Seitenebene Home ändert sich automatisch nach Aktualisierung

### ISSUE THREAD

**Issue by uwe367** [slackero/phpwcms#324]
phpwcms Version 1.9.31-dev (2021/10/15, r553).
Nach einer Neunistallation ist der Alias der obersten Ebene (ID 0) **index**. Nach einer Aktualisierung der Ebene wird der Alias automatisch von index zu **index-view** geändert was dann auch in der URL in der Adressleiste des Browsers zu sehen ist : `http://localhost/test2/index-view.html`
Das gleiche Verhalten besteht auch bei älteren Installationen die ein Update auf die neueste Version erhalten haben.
Der Alais ist manuell nicht mehr auf index zu ändern, es wird automatisch wieder index-view gesetzt.
So gewollt oder Bug?

**Comment by slackero** [comment]
Das ist so gewollt – soweit ich mich entsinne, um Probleme mit möglicherweise dort liegender index.html zu vermeiden.
