### ISSUE TITLE
Warnings bei CP "Text mit Bild"

### ISSUE THREAD

**Issue by uwe367** [slackero/phpwcms#327]
phpwcms 1.9.31-dev (2021/10/17, r553)
Bei der Verwendung des CP "Text mit Bild" werden im FE Warnings ausgegeben, z.B.:
`Warning: Undefined array key "imgtxt-top-left" in D:\xampp\htdocs\example\include\inc_front\content\cnt1.article.inc.php on line 53`
Für jede Bild- bzw. Textposition wird eine Meldung ausgegeben, insgesamt 14.
PHP 8.0.11

**Comment by slackero** [comment]
Prüfe Deine Installation, da ist etwas durcheinander. Ist nicht nachvollziehbar.

**Comment by uwe367** [comment]
Ich habe den Fehler gefunden, jedich weiß ich nuicht ob das ein Fehler von mir ist ode rvielleicht doch ein Systemfehler.
Ich habe in **template/inc_settings** eine eigene Datei angelegt, **my_settings.php** um dort die Änderungen, die ich ansonsten in der conf.template_default.inc.php gemacht hätte, abzulegen. Im folgenden sehen diese Änderungen so aus:

`<?php
// some more default classes
$template_default['classes'] = array(

'navlist-sub_no'                => 'nav-item',
'navlist-sub_first'             => '',
'navlist-sub_last'              => '',
'navlist-sub_parent'            => 'nav-item',
'navlist-asub_no'               => 'asub_no',
'navlist-asub_first'            => 'asub_first',
'navlist-asub_last'             => 'asub_last',
'navlist-link-class'            => '',
'navlist-navLevel'              => 'nav-level-',
'navlist-bs-link'               => 'nav-link',
'navlist-bs-dropdown'           => 'dropdown',
'navlist-bs-dropdown-toggle'    => 'dropdown-toggle',

);`

Nachdem ich diese Datei im Haupttemplate ausgewählt habe kam es zu diesen Fehlermeldungen. Nun weiß ich nicht ob ich bei der Schreibweise etwas falsch gemacht habe.
Kopiere ich den gesamten Inhalt der conf.template_default.inc.php in die my_settings.php klappt das ganze ohne Fehler.
Also gehe ich davon aus daß ich einen Fehler gemacht habe der zu der Fehlermeldung führte.

**Comment by slackero** [comment]
Leider Dein Fehler, Du überschreibst die Klassendefinitionen komplett, aber eben unvollständig.

Entweder:
```
$template_default['classes']['navlist-sub_no'] = 'nav-item',
// ...
$template_default['classes']['navlist-bs-dropdown-toggle'] = 'dropdown-toggle',
```
Oder:
```
$template_default['classes'] = array_merge($template_default['classes'], array(
'navlist-sub_no' => 'nav-item',
'navlist-sub_first' => '',
'navlist-sub_last' => '',
'navlist-sub_parent' => 'nav-item',
'navlist-asub_no' => 'asub_no',
'navlist-asub_first' => 'asub_first',
'navlist-asub_last' => 'asub_last',
'navlist-link-class' => '',
'navlist-navLevel' => 'nav-level-',
'navlist-bs-link' => 'nav-link',
'navlist-bs-dropdown' => 'dropdown',
'navlist-bs-dropdown-toggle' => 'dropdown-toggle',
));
```

**Comment by uwe367** [comment]
Ich dachte mir etwas in dieser Art. Danke für die Erläuterungen.
