### ISSUE TITLE
Warning bei CP "Bilder <div>"

### ISSUE THREAD

**Issue by uwe367** [slackero/phpwcms#328]
phpwcms 1.9.31-dev (2021/10/17, r553)
Im FE wird  bei der Verwendung des CP **Bilder div** eine Warning ausgegeben:
`Warning: Undefined array key "image-thumb" in D:\xampp\htdocs\example\include\inc_front\content\cnt29.article.inc.php on line 118`
PHP 8.0.11

Gerade getestet. Es werden bei Allen CP´s mit Bildern Warnings ausgegeben.

**Comment by slackero** [comment]
Verwandt mit Issue #327
