### ISSUE TITLE
RT {FE_USER_REGISTER} wird im FE nicht gerendert

### ISSUE THREAD

**Issue by uwe367** [slackero/phpwcms#329]
Version: phpwcms 1.9.31-dev (2021/10/17, r553)
Der RT `{FE_USER_REGISTER}` wird im FE in Textform ausgegeben und nicht gerendert.
Installation ist derzeit Standart der Neuinstallation und CP Template ist fe_login.tmpl aus dem Verzeichnis example.

**Comment by slackero** [comment]
Ohne aktive fe_user.php macht die Möglichkeit, dass sich ein neuer Nutzer registrieren oder sein Profil verwalten kann, keinen Sinn. Dann sollte auch diese Anzeige verschwunden sein.

**Comment by uwe367** [comment]
Ok, Danke.
