### ISSUE TITLE
Frontend Login, edit Userprofile funktioniert nicht

### ISSUE THREAD

**Issue by uwe367** [slackero/phpwcms#331]
phpwcms Version: 1.9.31-dev (2021/10/17, r553)
Frontend Login mit Standart Template.
Anmelden funktioniert problemlos.
Möchte ich jedoch mein Userprofil mittels Klick auf "edit your user profile" bearbeiten, erscheint lediglich die Meldung:
FE Login
Manage account
Diese Aktion ist leider nicht zulässig.
Wo könnte der Fehler liegen?

**Comment by q23** [comment]
Script nicht aktiv?
https://github.com/slackero/phpwcms/blob/master/template/inc_script/frontend_render/disabled/fe_user.php

**Comment by uwe367** [comment]
Doch, ist aktiv.
Gibt auch noch ein paar andere Probleme mit der "Passwort vergessen" Funktion, aber dazu werde ich demnächst Issues erstellen.

**Comment by df6ih** [comment]
Das war (damals) ein anderes Script ...evtl zusätzlich. Aber ob das jemals
fertig war? *Koppkratz*


Am Do., 20. Jan. 2022 um 17:48 Uhr schrieb Uwe Tholey <
***@***.***>:

**Comment by slackero** [comment]
Also das läuft alles, aber es braucht immer adäquate Konfiguration. Wichtig ist, darf der Nutzer überhaupt sein Profil bearbeiten. Profile aus den Backendbenutzer sind nicht im Frontend bearbeitbar. Das machen Nutzer über das Backend. Es muss der korrekte Alias/ID eingetragen werden, wo das Profil bearbeiten hinleiten soll.

**Comment by uwe367** [comment]
Ok, dann habe ich das falsch gedeutet.
Ich war der Ansicht dass der User durch diesen Link zum BE geleitet wird wo er dann eben das BE Profil aktualisieren kann.
Hat sich dann geklärt.
