### ISSUE TITLE
phpwcms 1.9.30 & 1.9.33 E-Mail Form Problems

### ISSUE THREAD

**Issue by eccentricworx** [slackero/phpwcms#335]
Hi there,

i´m new to github, so please excuse if i´m not doing it right, but i stumbled upon 3 Bugs in PHPWCMS and have to contribute.

- under PHP v8.0 & v8.1 E-Mails will be sent out in Text-Format instead of html, even if the selector is set for html option
- google recaptcha doesn´t work anymore, if integrated, form simply refreshes the page without any error-messages instead of sending out mails
Both problems appear mainly in Hosteurope hosted Websites, could this be a problem related to their PHP Configuration?

- radio-button: system opens a div tag around an inserted radio-button (class="form-radiobutton") , which isn´t closed by the responding php-file (cnt23.article.inc.php > line 1068), i think this appears as from version 1.9.30

**Comment by slackero** [comment]
> under PHP v8.0 & v8.1 E-Mails will be sent out in Text-Format instead of html, even if the selector is set for html option

I cannot confirm this behavior. Have you tried the dev release?

> google recaptcha doesn´t work anymore, if integrated, form simply refreshes the page without any error-messages instead of sending out mails

Which version of the captcha? I tested with v2 – works.

>   Both problems appear mainly in Hosteurope hosted Websites, could this be a problem related to their PHP Configuration?

can be, check error logs

> radio-button: system opens a div tag around an inserted radio-button (class="form-radiobutton") , which isn´t closed by the responding php-file (cnt23.article.inc.php > line 1068), i think this appears as from version 1.9.30

should be solved

**Comment by eccentricworx** [comment]
Hi, thanks for answering!

i did some more tests (PHP8 & PHP8.1)... Fresh install, Template contains only RT {CONTENT}, frontend.css, print_layout.css and jquery-3.6.0.min.js
Hoster is hosteurope

Re-Captcha V2 works at first, after pressing the send button this time i get this error message: _recaptcha-error:invalid-input-response_

As for the E-Mail Contents the Form is sending (without re-captcha) it still arrives as html in text-form (source-code), but works as expected in PHP 7.4

The error logs of the webspace show no errors at all.

I really have no clue what else to do, should i send you the phpinfo?

**Comment by slackero** [comment]
PHPinfo will not help. E-Mail was sent by method `mail` or `SMTP`? You have used the dev release?

How do you load the page with reCaptcha again, reload the once sent form or really open the page in a new window or hit enter in the address bar?

Double Opt-in selected or not? I think you have overseen this feature.

**Comment by eccentricworx** [comment]
I used the Dev Release, v1.9.33 and v1.9.30, phpmailer, Double Opt-in deactivated.
For testing i usually use a private window, caching disabled. To reload i use a new window and paste the address, but i also tested in a standard window with caching enabled with the same result.

**Comment by eccentricworx** [comment]
ok, i saw that the logging of hosteurope was kind of restrictive.
the log shows nothing, but finally i got this error message:

Warning: file_get_contents(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 in www/test/include/inc_lib/classes/class.recaptcha.php on line 71

Warning: file_get_contents(https://www.google.com/recaptcha/api/siteverify?secret=---------------------&remoteip=-------------------------------------------------&response=03ANYolqt2huJrutc1KVaE1s6Dgvagj61dP_XsoQ0q6dVrrVLLx61xS3V-1gNCgWHEGkRducBQP0z6NjxbDvqGZEOfQyjYwioQEnN1bBc-zJM1RbLFqKsMmuhEaCjYpaQmfRKlRjcmWKMOC-CDYrkoaHbYhyxYfRaIweMobjojzbBSC8B5k4YyCbrM9WjP1yVtOSqCh96aNiaPWWEH3glzICCO1PZ8jA3Eky8TotGga26wgrZYjPuXg7OiPsqIaC07oKcOdBb6uHCnmbRIIp94v0d7Nai-W8jZCfJ6nNkd1Ntlf-ubx7CdunXcFW8SRvQ3YORojv2a5dstFO5qK7fAnrWpU3HzkVbVet1kyJXygfEyXJNYwnDEqHgnZvWKMa3ed5IBJWI32OVmSB5bjTN-88EcPUmdI2u93ERoa7YYPTYSei8HPTfKdwvpuBSeco5IbqNdSeaaGDURxBRQrleM5JYM0A2eiBhf5EI-8Uq_SNSlPzpCRvtWt3iY1w51_wyYci7Ht0nfsqNvbAeUz0JABnFi5aXBftVqqo2zrhLvHdtW6PG0Sd7rc8DFirJH_uTZKPPz7-2gCqfAK8cWlPyD1LscxUsH9K2LsR75hDb93ks2s2cmRAz2SR0): Failed to open stream: no suitable wrapper could be found in www/test/include/inc_lib/classes/class.recaptcha.php on line 71

(filled some of the letters of the key with blanks... ;) )

**Comment by eccentricworx** [comment]
ok, i switched to allow_url_fopen=1, this is possible in the Script-Setting Page in Hosteuropes KIS. It solved the Google Re-Captcha Issue. You might want to make this Info Public with the next release... ?

But there is still the Problem that E-Mails will be sent out in Text-Format only, despite that in the form it´s set to html.

**Comment by slackero** [comment]
This is the latest dev release https://github.com/slackero/phpwcms/archive/refs/heads/v1.9-dev.zip 1.3.4-dev
You have used this?

**Comment by eccentricworx** [comment]
archive packed on 31.08.2022 11:39.
looks like it, yes.

**Comment by slackero** [comment]
Check again please, I have implemented a fallback in the commit 63d303d1e39ad5e47ce3b6486397d56c342f0ba0 which will mark the mail as a multi-part message. The HTML content will be converted to plain text in this case.

**Comment by eccentricworx** [comment]
I just tested it and it works!!!!!
Thank you, really appreciate it!
