### ISSUE TITLE
Fehlverhalten in der Dateizentrale beim Übertragen von Dateien an einen anderen User

### ISSUE THREAD

**Issue by uwe367** [slackero/phpwcms#336]
Version: phpwcms 1.9.35-dev (2022/10/03, r553)
In der Dateizentrale gibt es, meiner Meinung nach, ein Fehlverhalten des Systems beim Übertragen von Dateien an einen anderen User.
Folgende Hierachie:
Ich (Admin mit Adminrechten)
User1 (ohne Adminrechte)

Verzeichnisse Dateizentrale:
+Wurzelverzeichnis
++Ordner1
++Ordner2
usw....

Dateien sind bis zum jetzigen Zeitpunkt alle dem Admin zugeordnet.
Der neue User wurde erst nachträglich angelegt, nachdem bereits alle Dateien in ihre Verzeichnisse hochgeladen wurden.

Übertrage ich als Admin nun mittels Dateiaktionen alle Dateien des Verzeichnisses Ordner1 an User1, so werden diese übertragen und in das Wurzelverzeichnis von User1 gelegt. Bis dahin alles ok.

Gleichzeitig werden die Dateien aber im Verzeichnisbaum des Admins aus dem Verzeichnis entfernt und in das Wurzelverzeichnis des Admins gelegt.
Ist das so richtig?

Es sollte auch möglich sein, dass Unterverzeichnisse in der Dateizentrale ebenfalls an einen anderen User übertragen werden können, z.B. dass ich als Admin "Ordner1" mit dem gesamten Inhalt an "User1" übertragen könnte. Würde der Übersichtlichkeit sehr zugute kommen. Genauso sollte das dann auch in der umgekehrten Richtung, bzw. in gleicher Hierachieebene, funktionieren.

**Comment by slackero** [comment]
Es gab nie eine angedachte Funktionalität, Dateien zwischen Nutzern zu verschieben. Die Dateiaktionen sind irgendwann im Nachgang hineingeraten.

**Comment by uwe367** [comment]
Achso. Ich dachte, da wäre irgendwo ein Fehler unterlaufen.
Soll das dann als Standart so bleiben wie es ist oder willst Du da bei Gelegenheit eventuell nochmal nachbessern?
Ist, mMn, schon sinnvoll, dass beim übertragen von Artikeln auch die darin enthaltenen Dateien übertragen werden bzw. man die Dateien im Nachgang übertragen kann so dass der neue Besitzer uneingeschränkt damit arbeiten kann.

**Comment by slackero** [comment]
Ich habe es etwas überarbeitet, vor allem werden jetzt alle Nutzer im Menü ausgegeben, auch gelöschte und der eigene Nutzer. Die Mitteilung ist aber eigentlich klar, Dateien landen derzeit im Root des gewählten neuen Eigentümers.

Es wäre natürlich möglich, ein weiteres Order-Auswahlfeld einzubauen, in das dann die neuen Dateien einsortiert werden.

Gleichzeitig könnte man Admin-Nutzern ermöglichen, auch Dateien anderer Nutzer zu verschieben, gerade von gelöschten z.B. Wobei da dann Sinn machen würde, auch deren Ordnerstruktur zu bewahren.

**Comment by uwe367** [comment]
Vielen Dank Dir.
Ich probiere das aus und wenn "Handlungsbedarf" bestehen sollte, kontaktiere ich Dich.
