### ISSUE TITLE
Fehlermeldung mod_fcgid: stderr ... content.func.inc.php on line 454 (v1.9-php8.2-dev)

### ISSUE THREAD

**Issue by DanSch22** [slackero/phpwcms#339]
Hallo,

Ich habe meine Dev Version (v1.9-dev) per GIT auf den Branch v1.9-php8.2-dev aktualisiert und bekomme nun beim Zugriff auf die Seite folgende Server Fehlermeldung. Es wird kein Code ausgeliefert. Seite bleibt Leer.
Backend Login funktioniert.

Versionen:
phpwcms v1.9-php8.2-dev (2023/05/30, r553)
PHP Version 8.2.4
Mysql Version 8.0.33

Fehlermeldung:
`2023-06-03 15:08:03	Warning	xxx.xxx.xxx.xxx		mod_fcgid: stderr: PHP Parse error: syntax error, unexpected token "," in /var/www/vhosts/xxx/xxx/include/inc_front/content.func.inc.php on line 454				Apache-Fehler`

In der Historie ist zu sehen, dass am 30.05. Änderungen (#338) an der Datei an genau der Stelle gemacht wurden.
`-       $block = @unserialize($result[0]['template_var']);`
`+      $block = @$result[0]['template_var'], ['allowed_classes' => false]);`

Erklärt dies den Fehler?
Meine Dev Umgebung enthält keine Anpassungen. Es sind die Default Template Daten aus dem Repo.
Config Datei conf.inc.php ist mit der dist.conf.inc.php abgeglichen.

Muss ich von meiner Seite etwas anpassen?
Mit der Info "Updated composer packages (remember composer upgrade in the document root)" kann ich nichts anfangen.

**Comment by DanSch22** [comment]
Ich habe spontan mal folgendes getestet:
content.func.inc.php on line 454
```
// read the template information for the current page based on structure
if(!empty($content["struct"][ $content["cat_id"] ]["acat_template"])) {
    //if there is a template defined for this structure level
    //then choose the template information based on this ID
    $sql  = "SELECT template_var FROM ".DB_PREPEND."phpwcms_template WHERE template_trash=0 AND ";
    $sql .= "template_id=".$content["struct"][ $content["cat_id"] ]["acat_template"]." LIMIT 1";
    $result = _dbQuery($sql);
    if(isset($result[0]['template_var'])) {
#        $block = @$result[0]['template_var'], ['allowed_classes' => false]);
	 $block = @unserialize($result[0]['template_var'], ['allowed_classes' => false]);
	}
}
```
Frontend funktioniert damit wieder, aber wäre das so korrekt?

**Comment by q23** [comment]
Sieht stimmig aus. Push es doch mal an OG.

**Comment by DanSch22** [comment]
> Push es doch mal an OG.

Was meinst Du mit pushen?
Sieht OG das offene Ticket nicht?

**Comment by q23** [comment]
Pushen iSv Geänderten/ Optimierten/ Entstörten Code an den Entwickler übergeben.

**Comment by q23** [comment]
@slackero

**Comment by slackero** [comment]
Danke, erledigt
