### ISSUE TITLE
Fatal Error Shop Modul

### ISSUE THREAD

**Issue by uwe367** [slackero/phpwcms#340]
Bei einem Klick auf den Tab "Einstellungen" beim Shop Modul wird unten bei Versandkosten ein Fatal Error ausgegeben.
Klicke ich beispielsweise anschließend auf "Admin" oder einen anderen Link innerhalb des BE, werde ich aus dem BE raus geschmissen und muss mich neu anmelden.

Version:
phpwcms 1.9.36-dev (2023/05/28, r553)
PHP 8.0.1

**Comment by slackero** [comment]
Wie @q23 anmerkte, wie ist der Fehler? Hast Du alles bzgl. Shop-Modul konfiguriert?

**Comment by uwe367** [comment]
Ich habe dort gar nichts konfiguriert sondern einfach nur mal durch die Reiter geklickt und dabei die Meldung erhalten.
Fraglich ob das bei einem Modul, welches nicht genutzt wird, dann so richitg ist.
Unter PHP 7.4 gibts keine Fehlermeldung.
PHP Error Log mit PHP 8.0.1 sagt folgendes:
`PHP Fatal error:  Uncaught TypeError: number_format(): Argument #1 ($num) must be of type float, string given in D:\MAMP\htdocs\xxxx\include\inc_module\mod_shop\inc\edit.preferences.inc.php:132`

**Comment by slackero** [comment]
sollte abgefangen sein
