### ISSUE TITLE
Warnings CP Suche

### ISSUE THREAD

**Issue by uwe367** [slackero/phpwcms#341]
Nachdem ich einen CP Suche eingebaut habe und Suchen lasse, werden folgende Warnings ausgegeben:
Die Suche selbst funktioniert zwar und es werden entsprechene Ergebinsse ausgegeben, aber eben auch die Warnings.

phpwcms Version: 1.9.36 (2022/05/28, r553)
PHP Version: 8.0.1

`Warning: Undefined array key "cp-paginate" in D:\MAMP\htdocs\xxxx\include\inc_front\content\cnt13.article.inc.php on line 597

Warning: Trying to access array offset on value of type null in D:\MAMP\htdocs\xxxx\include\inc_front\content\cnt13.article.inc.php on line 597

Warning: Undefined array key "cp-paginate" in D:\MAMP\htdocs\xxxx\include\inc_front\content\cnt13.article.inc.php on line 608

Warning: Trying to access array offset on value of type null in D:\MAMP\htdocs\xxxx\include\inc_front\content\cnt13.article.inc.php on line 608`

**Comment by slackero** [comment]
Gleiche mal Deine template default config ab.Sollte zwar nicht passieren, aber dürfte helfen.

**Comment by uwe367** [comment]
Danke für den Hinweis bezüglich der conf.template_default.inc.php.
Ich merge eine custom-settings.php und da scheint irgendwo ein Fehler drin zu sein, den ich nicht sehe.
BIeibt die Datei, die gemerged wird, leer, gibt es keine Meldung.
Sobald ich diese Datei mit folgendem Inhalt merge, treten die Warnings auf.

` $template_default['classes'] = array_merge($template_default['classes'], array(

    `'navlist-sub_ul_true'           => 'sub_ul_true',
    'navlist-sub_ul'                => 'nav-item',
    'navlist-sub_no'                => 'nav-item',
    'navlist-sub_first'             => '',
    'navlist-sub_last'              => '',
    'navlist-sub_parent'            => 'nav-item',
    'navlist-asub_no'               => 'asub_no',
    'navlist-asub_first'            => 'asub_first',
    'navlist-asub_last'             => 'asub_last',
    'navlist-link-class'            => 'dropdown-item text wrap',
	'navlist-link-class'            => 'dropdown-item',
    'navlist-bs-dropdown-toggle'    => 'dropdown-toggle text-wrap',
	'navlist-bs-dropdown-toggle'    => 'dropdown-toggle',
));
$template_default['attributes'] = array(
    'navlist-bs-dropdown-data'  => 'data-bs-toggle="dropdown"',
    'navlist-bs-dropdown-caret' => '',
	); `

Was mich allerdings wundert ist, dass unter PHP 7x nur eine Notice ausgeben wird und unter PHP 5x keine Meldung erscheint.

**Comment by slackero** [comment]
Du machst für $template_default['attributes'] keinen Merge, sondern ersetzt das Array, damit löschst Du natürlich andere Properties. Mach es nicht so, wenn Du nur einzelne Werte überschreiben möchtest. Ist auch viel einfacher zu warten und zu lesen.
```
$template_default['attributes']['navlist-bs-dropdown-data']  = 'data-bs-toggle="dropdown"';
$template_default['attributes']['navlist-bs-dropdown-caret']  = '';
```

**Comment by uwe367** [comment]
Danke für den Hinweis.
Ich dachte mir schon, dass der Fehler bei mir liegt.
