### ISSUE TITLE
Warnings bei Artikelpaginierung

### ISSUE THREAD

**Issue by uwe367** [slackero/phpwcms#342]
Werden Artikel paginiert, kommt es zu folgenden Warnings:
`Warning: Undefined array key "cp-paginate" in D:\MAMP\htdocs\xxxx\include\inc_front\front.func.inc.php on line 1016
Warning: Trying to access array offset on value of type null in D:\MAMP\htdocs\xxxx\include\inc_front\front.func.inc.php on line 1016`
PHPWCMS Version: phpwcms 1.9.36-dev (2023/05/28, r553)
PHP Version: 8.0.1

**Comment by slackero** [comment]
Same problem as issue #341
