### ISSUE TITLE
Parse error bei Datei Mehrfachupload

### ISSUE THREAD

**Issue by uwe367** [slackero/phpwcms#344]
Möchte ich mehrere Dateien mittels Mehrfachupload hochladen, erhalte ich bei der Übernahme in Wurzelverzeichnis oder in ein anderes Verzeichnis einen Parse error:
`Parse error: syntax error, unexpected variable "$phpwcms" in D:\MAMP\htdocs\phpw-neu\include\inc_act\act_ftptakeover.php on line 12`
Einzelupload funktioniert.

Version: phpwcms 1.10.1-dev (2023/09/22, r554)
PHP Version: 8.2.1

**Comment by uwe367** [comment]
Habe das gerade mit der zuletzt bereit gestellten Version 1.10.1-dev (2023/09/22, r554) auf dem Server (all-inkl) unter PHP 8.2.9 getestet. Die Dateien (hier nur Bilder) werden beim Mehrfachupload in das ausgewählte Verzeichnis übernommen, aber in der Dateizentrale werden statt Vorschaubilder nur Icons angezeigt und das Einbinden in einen CP, z.B Bilder div, ist nicht möglich, da im Filebrowser keine Dateien zum auswählen angezeigt werden.
Ich erstelle Dir gerne einen Adminzugang zum System sowie einen FTP Zugang und lasse Dir die Daten per Mail zukommen.

**Comment by slackero** [comment]
War Folgefehler, müsste jetzt gelöst sein.

**Comment by uwe367** [comment]
Ja, klappt jetzt. Danke Dir 👍
