### ISSUE TITLE
Artikellzentrale, Meldungen nach anlegen neuer Artikel

### ISSUE THREAD

**Issue by eccentricworx** [slackero/phpwcms#346]
Nach Anlgen eines Artikels (mit als auch ohne Start/Enddatum) werden in der Artikelzentrale mehrere Meldungen über der Artikelliste angezeigt:

Warning: Undefined array key "article_begin" in /is/htdocs/wp13003637_I3ITEMMQCMN/www/test/include/inc_lib/admin.functions.inc.php on line 268
Warning: Undefined array key "article_end" in /is/htdocs/wp13003637_I3ITEMMQCMN/www/test/include/inc_lib/admin.functions.inc.php on line 272
Warning: Undefined array key "article_begin" in /is/htdocs/wp13003637_I3ITEMMQCMN/www/test/include/inc_lib/admin.functions.inc.php on line 268
Warning: Undefined array key "article_end" in /is/htdocs/wp13003637_I3ITEMMQCMN/www/test/include/inc_lib/admin.functions.inc.php on line 272
Warning: Undefined array key "article_begin" in /is/htdocs/wp13003637_I3ITEMMQCMN/www/test/include/inc_lib/admin.functions.inc.php on line 268
Warning: Undefined array key "article_end" in /is/htdocs/wp13003637_I3ITEMMQCMN/www/test/include/inc_lib/admin.functions.inc.php on line 272
Warning: Undefined array key "article_begin" in /is/htdocs/wp13003637_I3ITEMMQCMN/www/test/include/inc_lib/admin.functions.inc.php on line 268
Warning: Undefined array key "article_end" in /is/htdocs/wp13003637_I3ITEMMQCMN/www/test/include/inc_lib/admin.functions.inc.php on line 272
Warning: Undefined array key "article_begin" in /is/htdocs/wp13003637_I3ITEMMQCMN/www/test/include/inc_lib/admin.functions.inc.php on line 268
Warning: Undefined array key "article_end" in /is/htdocs/wp13003637_I3IJTAQCMN/www/test/include/inc_lib/admin.functions.inc.php on line 272

Nach refresh der Artikelzentrale wieder normal.

phpwcms 1.10.1-dev (2023/09/22, r554)
PHP Version 8.2.9-he.0

**Comment by uwe367** [comment]
Kann ich bestätigen.
Ist unter PHP 8.2.1 das gleiche.
Nach erneutem Laden der Artikelzentrale sind die Fehler verschwunden.
