### ISSUE TITLE
Artiklel-/Contentpart-datum nach update

### ISSUE THREAD

**Issue by eccentricworx** [slackero/phpwcms#347]
Nach Update von v1.9.36 bekommen alle Artikel und Contentparts das gleiche letzte Änderungsdatum und Uhrzeit des Zeitpunkts der Re-Initialisierung zugewiesen. Ist nicht weiter schlimm, macht allerdings einiges unübersichtlich...

phpwcms 1.10.1-dev (2023/09/22, r554)
PHP Version 8.2.9-he.0

**Comment by slackero** [comment]
Habe eine Lösung dafür integriert, die verhindern sollte, dass der Wert mit Upgrade von Tabellenspalten neu gesetzt wird.
