### ISSUE TITLE
Artikelbasis Bild Artikeldetail führt zu Fatal Error

### ISSUE THREAD

**Issue by uwe367** [slackero/phpwcms#348]
Verwende ich in der Artikelbasis ein Bild bei **Bild: Artikeldetail**, führt dies bei der Verwendung von **Galeriebild** zu einem Fatal Error.
PHP error.log sagt dann folgendes:

```
PHP Fatal error:  Uncaught Error: Call to undefined function initSlimbox() in /www/htdocs/xxxx/versuch.uwe367.de/include/inc_front/content.article.inc.php:328
Stack trace:
#0 /www/htdocs/xxxx/versuch.uwe367.de/include/inc_front/content.func.inc.php(711): include_once()
#1 /www/htdocs/xxxx/versuch.uwe367.de/index.php(69): require('/www/htdocs/w00...')
#2 {main}
  thrown in /www/htdocs/xxxx/versuch.uwe367.de/include/inc_front/content.article.inc.php on line 328
```

Ähnlich verhält es sich, wenn ich Bilder in einem CP Bilder  div einbaue und Galeriebild verwende:
```
PHP Fatal error:  Uncaught Error: Call to undefined function initSlimbox() in /www/htdocs/xxxx/versuch.uwe367.de/include/inc_front/content/cnt29.article.inc.php:132
Stack trace:
#0 /www/htdocs/xxxx/versuch.uwe367.de/include/inc_front/content.article.inc.php(615): include()
#1 /www/htdocs/xxxx/versuch.uwe367.de/include/inc_front/content.func.inc.php(711): include_once('/www/htdocs/w00...')
#2 /www/htdocs/xxxx/versuch.uwe367.de/index.php(69): require('/www/htdocs/w00...')
#3 {main}
  thrown in /www/htdocs/xxxx/versuch.uwe367.de/include/inc_front/content/cnt29.article.inc.php on line 132
```
phpwcms Version: phpwcms 1.10.1-dev (2023/09/30, r554)
PHP Version: 8.2.9 all-inkl

Merkwürdig ist, dass lokal unter MAMP mit PHP 8.2.1 sowie PHP 8.2.10 alles normal und fehlerfrei läuft und nichts in die error.log geschrieben wird.

Wenn benötigt stelle ich Dir gerne entsprechende Zugänge zum System bzw. FTP zur Verfügung.

**Comment by slackero** [comment]
Prüfe mal Deine Vorlage, eigentlich sollte das nicht möglich sein. Ist dort jQuery ausgewählt?

**Comment by uwe367** [comment]
Ja, es ist jquery 3.7.1 mit CDN nutzen vorausgewählt.
Aber jetzt wird es merkwürdig, denn nach dem Öffnen der Vorlage und erneutem speichern ist der Fehler weg. Es handelt sich bei der Installation um eine frische Installation, an der keine Veränderungen vorgenommen wurden, also Standarttemplate.

Nach einem erneuten Test habe ich aber folgendes Verhalten im Quellcode gefunden:
Nach einer frischen Installation, keine Änderungen an der Vorlage vorgenommen, bekomme ich folgenden Quellcode, wenn ich Bilder einbaue, die als Galeriebilder (Lightbox) geöffnet werden sollen:
```
  <script src="template/lib/jquery/jquery-1.3.2.min.js"></script>
  <link href="template/lib/slimbox/slimbox.css" rel="stylesheet" type="text/css" media="screen" />
  <script src="template/lib/slimbox/slimbox.jquery.js"></script>
```
In der Vorlage ist Standartmäßig nach einer Neuinstallation jquery 3.7.1 mit CDN benutzen vorausgewählt, jedoch wird jquery 1.3.2 aus der lokalen Umgebung geladen.


Öffne ich die Vorlage und speichere sie erneut ohne irgendwelche Änderungen daran vorgenommen zu haben, bekomme ich folgenden Quellcode:
```
  <!--[if gte IE 9]><!--><script src="http://code.jquery.com/jquery-3.7.1.min.js"></script><!--<![endif]-->
  <link href="template/lib/slimbox/slimbox.css" rel="stylesheet" type="text/css" media="screen" />
  <script src="template/lib/slimbox/slimbox.jquery.js"></script>
```
Erst nach dem erneuten speichern wird die jquery Version geladen, die in der Vorlage voreingestellt ist und dann auch über CDN.

Wäre es möglich, dass die Fehler durch dieses Verhalten entstanden sind?

**Comment by slackero** [comment]
Das ist dem Alter der Vorlage geschuldet. Fällt auf jQuery 1.3.2 zurück, die nur noch als Deprecated in der Auswahlliste auftaucht. Trotzdem funktioniert der Fallback im Frontend. Bei Template-Wahl im Backend gibt es das aber nicht und die neueste wird standardmäßig gelistet.

Habe jetzt simple Lösung integriert, sodass man sieht, dass die gerade gewählte JS-Lib veraltet ist. 

<img width="627" alt="Bildschirmfoto 2023-10-03 um 09 39 45" src="https://github.com/slackero/phpwcms/assets/15139/fcc52215-23f9-41ed-a131-28f678274de2">

**Comment by uwe367** [comment]
Danke Dir 👍
