### ISSUE TITLE
Fatal error bei Installation phpwcms 1.10.

### ISSUE THREAD

**Issue by uwe367** [slackero/phpwcms#350]
Version: phpwcms 1.10
Bei der Installation wird, wenn ich eine nicht vorhandene Datenbank angebe, ein Fatal error auf weißem Bildschirm ausgegeben.

`Fatal error: Uncaught mysqli_sql_exception: Unknown database 'test' in D:\MAMP\htdocs\xxx\setup\inc\setup.check.inc.php:86 Stack trace: #0 D:\MAMP\htdocs\xxx\setup\inc\setup.check.inc.php(86): mysqli_connect('p:localhost', 'root', Object(SensitiveParameterValue), 'test') #1 D:\MAMP\htdocs\xxx\setup\setup.php(30): require_once('D:\\MAMP\\htdocs\\...') #2 {main} thrown in D:\MAMP\htdocs\xxx\setup\inc\setup.check.inc.php on line 86`

Klar, dass bei einer nicht vorhandendenen DB ein Fehler auftritt, aber war das früher nicht so, dass in dem Fall ein Hinweis zur Überprüfung der DB Verbindung angezeigt wurde?

**Comment by slackero** [comment]
Sollte jetzt abgefangen werden mittels `try {} catch()`. Noch DB Port eingeführt.

**Comment by uwe367** [comment]
Super, funktioniert jetzt.
Danke Dir.
