### ISSUE TITLE
Webp support

### ISSUE THREAD

**Issue by tomjak** [slackero/phpwcms#352]
Please add "webp" support to the "$phpwcms['allowed_upload_ext']" configuration (dist.conf.inc.php).

**Comment by slackero** [comment]
It's already there since a long time https://github.com/slackero/phpwcms/blob/master/include/config/dist.conf.inc.php#L144

**Comment by tomjak** [comment]
This is true, but a clean installation of phpWCMS does not add the "webp" format to the "conf.inc.php" configuration file. The "setup.conf.inc.php" file also lacks the "webp" format.

**Comment by slackero** [comment]
This is something else, done
