### ISSUE TITLE
.webp support

### ISSUE THREAD

**Issue by tomjak** [slackero/phpwcms#353]
phpWCMS 1.10.2 / php 8.2
File Center does not correctly support files in the .webp format. No image preview, the file cannot be added to the article. Some files display and work properly, others do not.

![Screenshot 2024-02-09 at 14-45-38 Zaplecze phpwcms (administracja) - localhost_phpwcms-1_10](https://github.com/slackero/phpwcms/assets/4180484/a71e04ee-e986-4aff-bbb7-5ab7b07c0a2f)

phpWCMS 1.9.35 / php 7.4 / php 8.2 - works fine on the same files.

**Comment by Chaffinch** [comment]
My hosting provider is KEI. For now, I'm staying on the older version >> phpWCMS 1.9.35 <<. phpWCMS 1.10.2 on KEI.pl servers , I don't succeed (I'm waiting for more stable Kei.pl software). Home.pl też poop. Best regards from the south

**Comment by tomjak** [comment]
I checked clean installs of 1.9.35/6/7/8. This error does not occur until 1.9.36. This error has been present since 1.9.37. Test environment: php 8.2.12 (XAMPP)

**Comment by Chaffinch** [comment]
Testing environment: php 8.2.12 (XAMPP) , O.K Let's wait for the knowledge to be supplemented. Regards

**Comment by tomjak** [comment]
In the file "helper.image.php" (phpWCMS 1.9.37) I found the following code:

```
                // Animated WebP isn't supported yet, needs to be detected and rejected
                $webp_type = file_get_contents($path, false, null, 12, 4);
                if ($webp_type && strtoupper($webp_type) === 'VP8X') {
                    $this->set_error('imglib_webp_animated_not_supported');
                    return false;
                }
```

I removed this code and my problem disappeared. My .webp files are not animated. Perhaps Photoshop, when exporting the image to the .webp format, consists of several layers, added information or the extended version VP8X.

**Comment by slackero** [comment]
WebP support of the GD lib is still not perfect – the problem might be resizing, I haven't tested it yet finally. I cannot recommend using WebP as default image format in the backend because of the possible lack of support in older browsers. And whenever possible switch to ImageMagick or GraphicMagic from GD. I will implement another setting which will override the VP8X check.

**Comment by slackero** [comment]
I have searched a bit more and found [a solution here](https://stackoverflow.com/questions/45190469#answer-73170213) (I hope). This works now for animated WebP too – just resizing is forbidden in combination with GD. An animated WebP example [can be found here](https://mathiasbynens.be/demo/animated-webp).

**Comment by tomjak** [comment]
Thanks for explanation.
I switched to the webp format a year ago. Tests showed no problems. Frontend and backend works properly.
The webp format makes it easier to achieve better Core Web Vitals results. I will not go back to the jpg format.
Your fix works very well. Thank you very much. 🏆
