### ISSUE TITLE
Missing translations (PL)

### ISSUE THREAD

**Issue by tomjak** [slackero/phpwcms#354]
I added the missing translations of the Polish version (phpwcms 1.10.2).
File: \include\inc_lang\backend\pl\lang.inc.php

```
$BL['be_hidden_for_feuser'] = 'Ukryty dla zalogowanych użytkowników serwisu';
$BL['be_visible_for_everybody'] = 'Widoczny dla wszystkich (domyślnie)';
$BL['be_robots'] = 'Indeks wyszukiwarek';
$BL['be_robots_noindex'] = 'blokuj indeksowanie wyszukiwarek (noindex)';
```

Please update.

**Comment by Chaffinch** [comment]
I need to check all my language files for (phpwcms 1.10.2). But thanks for the information

**Comment by Chaffinch** [comment]
If you have any suggestions look here: https://github.com/Chaffinch/phpwcms-1.10.2/tree/main/inc_lang . Corrections not yet submitted

**Comment by Chaffinch** [comment]
https://github.com/Chaffinch/phpwcms-1.10.2/blob/main/inc_lang/backend/pl/lang.inc.php      O.K. updated as suggested

**Comment by tomjak** [comment]
Thanks for update.

Suggested corrections to the file:
include/inc_lang/formmailer/lang.formmailer.inc.php

```
// Language: Polish, Language Code: pl UTF-8 for ver.1.10.2 (2024/01/06, 554)
$translate["EN"]["error100"]		= "Nieprawidłowy adres e-mail odbiorcy.";
$translate["EN"]["error200"]		= "Brak tematu wiadomości!";
$translate["EN"]["error300"]		= "Nieprawidłowy adres e-mail do wysłania wiadomości potwierdzającej.";

```
Instead of:
$translate["EN"]...

should be for all entries:

$translate["PL"]...
?

**Comment by Chaffinch** [comment]
"error300" It's ok ->PL , I added

**Comment by slackero** [comment]
Maybe prepare a pull request.

**Comment by slackero** [comment]
I have added the translations

**Comment by tomjak** [comment]
Excellent.
