### ISSUE TITLE
Image Gallery

### ISSUE THREAD

**Issue by Chaffinch** [slackero/phpwcms#355]
Image Gallery Ich versuche zu erstellen als:

Ich bekomme Fehlermeldungen
Grafik DIV used as Slimbox v2.05

Fatal error: Uncaught Error: Call to undefined function initSlimbox() in /home/users/ikr.../public_html/phpwcms/include/inc_front/content/cnt29.article.inc.php:132 Stack trace: #0 /home/users/ikr.../public_html/phpwcms/include/inc_front/content.article.inc.php(615): include() #1 /home/users/ikr.../public_html/phpwcms/include/inc_front/content.func.inc.php(711): include_once('/home/users/ikr...') #2 /home/users/ikr.../public_html/phpwcms/index.php(69): require('/home/users/ikr...') #3 {main} thrown in /home/users/ikr.../public_html/phpwcms/include/inc_front/content/cnt29.article.inc.php on line 132

Grafik

Fatal error: Uncaught Error: Call to undefined function initSlimbox() in /home/users/ikr.../public_html/phpwcms/include/inc_front/content/cnt2.article.inc.php:78 Stack trace: #0 /home/users/ikr.../public_html/phpwcms/include/inc_front/content.article.inc.php(615): include() #1 /home/users/ikr.../public_html/phpwcms/include/inc_front/content.func.inc.php(711): include_once('/home/users/ikr...') #2 /home/users/ikr.../public_html/phpwcms/index.php(69): require('/home/users/ikr...') #3 {main} thrown in /home/users/ikr.../public_html/phpwcms/include/inc_front/content/cnt2.article.inc.php on line 78

Server:
Server API Apache 2.0 Handler 
PHP Version 8.2.15
System Linux

**Comment by slackero** [comment]
You have selected a JavaScript lib in the template?

**Comment by Chaffinch** [comment]
Ich glaube schon .Ich habe einen Testartikel und eine Galerie hinzugefügt. Ich habe eine Vorschau erstellt, ich habe diese Fehler. In der Vorlage habe ich die Bibliothek geändert in JQuery 3.4.1 ,das Problem ist verschwunden.

**Comment by Chaffinch** [comment]
![Screenshot 2024-02-28 at 05-19-45 Zaplecze phpwcms (administracja)](https://github.com/slackero/phpwcms/assets/4220798/379e18b8-f3a7-42f0-83fa-c2081d479716)

**Comment by slackero** [comment]
As you have found out that it's required to have a JavaScript lib selected, otherwise it does not work.

I have implemented a fallback to avoid this.

**Comment by Chaffinch** [comment]
Slimbox v2.05 multilang switch
https://github.com/Chaffinch/phpwcms-1.10.2-lang-pl/commit/2e219d2a5b0005df65afa4bebaf684295ae7d05c
Oliver please let me know if the German tags are displayed correctly:    nextlabel-de.gif, closelabel-de.gif,prevlabel-de.gif
The test is here: http://1.10.2.foto.malopolska.pl/  Thanks for the info

**Comment by slackero** [comment]
Yes, it's German.

<img width="422" alt="Bildschirmfoto 2024-03-01 um 22 45 49" src="https://github.com/slackero/phpwcms/assets/15139/10a9c838-f1e6-4209-93a2-058213fa5f18">

**Comment by slackero** [comment]
> Slimbox v2.05 multilang switch [Chaffinch/phpwcms-1.10.2-lang-pl@2e219d2](https://github.com/Chaffinch/phpwcms-1.10.2-lang-pl/commit/2e219d2a5b0005df65afa4bebaf684295ae7d05c) Oliver please let me know if the German tags are displayed correctly: nextlabel-de.gif, closelabel-de.gif,prevlabel-de.gif The test is here: http://1.10.2.foto.malopolska.pl/ Thanks for the info

Remember that there usually is no JavaScript required any longer. CSS with the :lang() selector works very well.

```css
html:lang(de) #lbPrevLink:hover {
	background: transparent url(prevlabel-de.gif) no-repeat 0 15%;
}
html:lang(pl) #lbPrevLink:hover {
	background: transparent url(prevlabel-pl.gif) no-repeat 0 15%;
}
```

**Comment by Chaffinch** [comment]
Vielen Dank, ich wünsche Ihnen ein schönes Wochenende
