### ISSUE TITLE
Update auf 1.10.2

### ISSUE THREAD

**Issue by dieterbahr** [slackero/phpwcms#356]
Hab das Problem, das in sämtlichen Artikeln unter
Anzeige von: 0000-00-00 00:00:00 bis: 0000-00-00 00:00:00 drin stand und so keine Artikelinhalte mehr angezeigt wurden.
Hab das nun in allen Artikeln händisch geändert.
Jetzt wollte ich einen neuen News Artikel anlegen und es zeigt mir folgendes:

Unter 1.9.33 läuft alles prima

**Comment by dieterbahr** [comment]
Habe jetzt nochmals einen Update versuchte.
Problem mit dem Datum im Artikel habe ich nochmal händisch gemacht.
Habe aber auch festgestellt das es da eine Fehlermeldung in NEWS gibt.
Und zwar: 
fotografierbahr_https/include/inc_front/content/cnt33.article.inc.php(20): unserialize('a:13:{s:9:"news...', Array, Array) 

Die Zeile ist:  $news = @unserialize($crow["acontent_form"], ['allowed_classes' => false], ['allowed_classes' => false]);
Ersetze ich die durch die aus der Version 1.9.33 ist die Fehlermeldung weg und alles funktioniert

**Comment by slackero** [comment]
ich beantworte das in Deinem Artikel im Forum https://forum.phpwcms.org/posting.php?mode=reply&t=26457. Da hast Du einiges durcheinandergebracht und vermutlich nicht korrekt aktualisiert. Immer erst eine Kopie vollständig ans Laufen bringen und darauf das Update anwenden.
