### ISSUE TITLE
MySQL error: The maximum column size is 767 bytes

### ISSUE THREAD

**Issue by q23** [slackero/phpwcms#358]
Fehlermeldung beim aufsetzen: [MySQL error: The maximum column size is 767 bytes](https://stackoverflow.com/questions/30761867/mysql-error-the-maximum-column-size-is-767-bytes)

767 bytes in MySQL version 5.6 (and prior versions), is the stated prefix limitation for InnoDB tables. It’s 1,000 bytes long for MyISAM tables. This limit has been increased to 3072 bytes In MySQL version 5.7 (and upwards).

Ich hab nun das : COLLATE utf8_general_ci
mit: COLLATE utf8_general_ci ROW_FORMAT=DYNAMIC

**Comment by slackero** [comment]
Thanks for reporting and a possible solution. I have added a small change to (hopefully, untested) force this on MySQL config level while creating the initial database.
