### ISSUE TITLE
1.10.3-dev Uncaught TypeError

### ISSUE THREAD

**Issue by q23** [slackero/phpwcms#359]
CP Teaser in manuell select mode contains at least one invisible/ deactivated articel.
This error occures in different phpwcms (all with version 1.10.3-dev) on different systems:

Fatal error: Uncaught TypeError: Cannot access offset of type string on string in website/include/inc_front/content.article.inc.php:874 Stack trace: #0 website/include/inc_front/content.func.inc.php(711): include_once() #1 website/index.php(69): require('/homepages/5/d3...') #2 {main} thrown in website/include/inc_front/content.article.inc.php on line 874

**Comment by slackero** [comment]
I have refactored that section, hopefully it works. I have no time to test it. Please send me feedback – might happen if there were no article ID given and $row comes from "outside" as type string instead of type array as expected.

**Comment by q23** [comment]
works like a charm. thanks!

**Comment by q23** [comment]
works like a charm. thanks!
