### ISSUE TITLE
Fatal error: Uncaught mysqli_sql_exception while installing phpwcms 1.10.3

### ISSUE THREAD

**Issue by prbt2016** [slackero/phpwcms#361]
Hello,

I was in the process of manual installation of phpwcms 1.10.3 on AlmaLinux release 8.10 (Cerulean Leopard) with Apache 2.4.54, PHP 8.2.21, MYSQL 5.7.42. 

However, i faced an issue while doing so. 

On checking 'Create  database tables' and clicking 'Continue' , I get the following error i.e : 

```
Fatal error: Uncaught mysqli_sql_exception: Variable 'innodb_default_row_format' is a GLOBAL variable and should be set with SET GLOBAL in /{{PATH]]/{{TO}}/{{PHPWCMS}}/setup/inc/setup.check.inc.php:173 Stack trace: #0 /{{PATH]]/{{TO}}/{{PHPWCMS}}/setup/inc/setup.check.inc.php(173): mysqli_query(Object(mysqli), 'SET innodb_defa...') #1 /{{PATH]]/{{TO}}/{{PHPWCMS}}/setup/setup.php(30): require_once('/{{PATH]]/{{TO}}/{{PHPWCMS}}...') #2 {main} thrown in /{{PATH]]/{{TO}}/{{PHPWCMS}}/setup/inc/setup.check.inc.php on line 173 
```

![image](https://github.com/user-attachments/assets/3a0ac769-dfec-47e5-b46d-159d098ec35a)

What could be the issue ?. Could you please check and replicate this at your end and fix this?. 

Regards.

**Comment by slackero** [comment]
Can you try to change the file [setup/inc/setup.check.inc.php](https://github.com/slackero/phpwcms/commit/675941804fbd43436036eccae58d64350476d0d3#diff-81667aeab941e3fa487c21a4bed8894bf72206efcd242b35757b2399603b13ec)

**Comment by prbt2016** [comment]
Hello @slackero ,

After trying with this new setup file [setup/inc/setup.check.inc.php](https://github.com/slackero/phpwcms/commit/675941804fbd43436036eccae58d64350476d0d3#diff-81667aeab941e3fa487c21a4bed8894bf72206efcd242b35757b2399603b13ec) installation works fine .

Regards.

**Comment by slackero** [comment]
Thanks for the feedback
