### ISSUE TITLE
Parsedown 2.0 doesn't use Parsedown::text() anymore, but Parsedown::toHTML()

### ISSUE THREAD

**Issue by marcus-at-localhost** [slackero/phpwcms#363]
Got the same error in the plaintext cp with Markdown as https://github.com/slackero/phpwcms/issues/360

Unfortunately, the Parsedown 2.0 Docs are not updated but `Parsedown->text()` is wrong and doesn't exist in https://github.com/erusev/parsedown/blob/v2.0.0-beta-1/src/Parsedown.php anymore, instead use `Parsedown->toHtml($markdown) ` 

https://github.com/erusev/parsedown/pull/708#issuecomment-944799267

(Sent a pull request)

**Comment by slackero** [comment]
I just switched to another MarkDown parser which is still maintained.
