### ISSUE TITLE
Fatal error: Uncaught TypeError

### ISSUE THREAD

**Issue by q23** [slackero/phpwcms#364]
Fatal error: Uncaught TypeError: substr(): Argument #3 ($length) must be of type ?int, string given
V1.10.2 (2024/01/06, r554).

Change line here
https://github.com/slackero/phpwcms/blob/0294407331dafd72ca34d863f0fa84baf8716938/include/inc_front/content/cnt23.article.inc.php#L2014
to
$cnt_form["alt_subj"] = substr($cnt_form["alt_subj"], 0, intval(trim($phpwcms['site'], '/')));

**Comment by slackero** [comment]
Should be fixed, this must be very old. Thanks for finding.
