### ISSUE TITLE
Fatal error: Uncaught Error: Class "Locale" not found

### ISSUE THREAD

**Issue by DanSch22** [slackero/phpwcms#365]
Hello,
I done an upgrade of my website from phpwcms 1.10.2 to
```
const PHPWCMS_VERSION = '1.10.6';
const PHPWCMS_RELEASE_DATE = '2024/08/24';
const PHPWCMS_REVISION = '554';
```
at my local test server and now I get the following frontend error when I browse to news article. Other article types are not affected.
```
Fatal error: Uncaught Error: Class "Locale" not found in /<path>/include/vendor/php81_bc/strftime/src/php-8.1-strftime.php:45 Stack trace: #0 /<path>/include/inc_front/content/cnt7.article.inc.php(247): PHP81_BC\strftime('%m/%d/%y', Object(DateTime), 'en_GB') #1 /<path>/include/inc_front/content/cnt33.article.inc.php(814): include('/<path>...') #2 /<path>/include/inc_front/content.article.inc.php(615): include('/<path>...') #3 /<path>/include/inc_front/content.func.inc.php(711): include_once('/<path>...') #4 /<path>/index.php(69): require('/<path>...') #5 {main} thrown in /<path>/include/vendor/php81_bc/strftime/src/php-8.1-strftime.php on line 45
```
I saw changes to the `php-8.1-strftime.php` file:
https://github.com/slackero/phpwcms/commit/2dd77e505bf2489d9d17f3f4bf38cdfe8391f0e7#diff-ff84553acfb35fbfa7d9e9128f0de8c4e571c72e5700a78a83043b8988c73f5eL45

Then I upgraded my dev website to 1.10.6 too and tried to trigger the issue, but there I cannot reproduce this error.

Is there something wrong with settings at my local test server (Apache, PHP 8.2.0)?

**Comment by slackero** [comment]
Maybe you do not use all required php extensions locally:
https://github.com/filesender/filesender/issues/1943

**Comment by DanSch22** [comment]
Thank you.
That was the problem. Installed it at the local test server and all went fine now. Dev server had it already installed.

https://github.com/filesender/filesender/issues/1943#issuecomment-2188507202
> Ah. Missed the dependency to php-intl.
> 
> For future reference and searchengines: Install the `php-intl` module, restart php and webserver, and all will be fine.
