### ISSUE TITLE
Fatal error: Uncaught mysqli_sql_exception

### ISSUE THREAD

**Issue by q23** [slackero/phpwcms#366]
phpwcms 1.10.3-dev (2024/07/06, r554).

If News with in contentpart choosen Tags not available sites drops a 500 error
error prompt:
Fatal error: Uncaught mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-3, 3' at line 1 in /include/inc_lib/dbcon.inc.php:98 Stack trace: #0 /include/inc_lib/dbcon.inc.php(98): mysqli_query(Object(mysqli), 'SELECT pc.*, IF...') #1 /include/inc_front/content/cnt33.article.inc.php(344): _dbQuery('SELECT pc.*, IF...') #2 /include/inc_front/content.article.inc.php(615): include('/...') #3 /include/inc_front/content.func.inc.php(711): include_once('/...') #4 /index.php(69): require('/var/www/web11/...') #5 {main} thrown in /include/inc_lib/dbcon.inc.php on line 98

**Comment by q23** [comment]
now this appears

Fatal error: Uncaught ArgumentCountError: unserialize() expects at most 2 arguments, 3 given in /include/inc_front/content/cnt33.article.inc.php:20 Stack trace: #0 /include/inc_front/content/cnt33.article.inc.php(20): unserialize('a:13:{s:9:"news...', Array, Array) #1 /include/inc_front/content.article.inc.php(615): include('/var/www/web11/...') #2 /include/inc_front/content.func.inc.php(711): include_once('/var/www/web11/...') #3 /index.php(69): require('/var/www/web11/...') #4 {main} thrown in /include/inc_front/content/cnt33.article.inc.php on line 20

**Comment by slackero** [comment]
Line 20 should look like this:
`$news = @unserialize($crow["acontent_form"], ['allowed_classes' => false]);`

**Comment by slackero** [comment]
@q23 Could you solve the problem?

**Comment by q23** [comment]
Not now, we replaced the whole cnt33.article.inc.php, but the page remains blank

**Comment by q23** [comment]
i just realized that there are patches for two versions. i tried the wrong one. with the right one it works with the neighbor (to quote an old forum user ;))

**Comment by q23** [comment]
i just realized that there are patches for two versions. i tried the wrong one. with the right one it works with the neighbor (to quote an old forum user ;))
