### ISSUE TITLE
MySQL Improved Extension Support

### ISSUE THREAD

**Issue by marcus-at-localhorst** [slackero/phpwcms#55]
Any plans to move to mysqli extension in future?
https://wikis.oracle.com/display/mysql/Converting+to+MySQLi

best marcus.

**Comment by slackero** [comment]
lot of work, will come with the next bigger release because I have to touch all queries.

**Comment by marcus-at-localhorst** [comment]
It's not urgent, though.

**Comment by marcus-at-localhorst** [comment]
Do you think it's possible to keep all the `dbGet()` `dbUpdate()` etc calls and just rewrite the function behind it, to use PDO? I guess then there is no benefit of parameterized queries anymore, right?. Or just replace all `mysql_*` functions with `mysqli_*`, at least for the short term.
Just curious.

**Comment by slackero** [comment]
It's the plan to update this with 1.9.0 scheduled by the end of this year. For me it is urgent — but needs time as always. 1.8.0 brought more security, the next will bring more compatibility and flexibility. Migrating the database query related code should stick with phpwcms' custom DB wrapper. This also means to replace all existing native mysql functionality by a wrapper based one.

I also thought about stored procedures and views, with PDO it might be too complex, has to be sorted out.
