### ISSUE TITLE
Fremde Bilder lassen sich nicht löschen

### ISSUE THREAD

**Issue by kukki15344** [slackero/phpwcms#99]
In Dateiverzeichnis lassen sich aus einigen Verzeichnissen einige Bilder nicht mehr löschen, allerdings kann man "aktiv" und "öffentlich" verstellen. Arbeite hier mit der allerneusten Version vom 10.09.2014.
Diese bestreffenden Bilder werden auch bei Dateiaktionen nicht angezeigt, so dass ich diese nicht einmal mir selber als Admin zuordnen kann.

![fehlerbilder](https://cloud.githubusercontent.com/assets/6285517/4238340/998a7470-39d7-11e4-8cee-93f53d4fa7a6.jpg)

**Comment by q23** [comment]
vielleicht wäre es schön eine praktikalbe lösung dem admin wirklich komplette rechte über die dateien zu geben bzw. ähnlich den contentparts auch dieses "recht" zuweisen zu können. dies aktuelle situation ist -gesamt phpwcms betrachtet- mir auch am praxisfernsten bzw. inkonsistentesten umgesetzt (da wirklich nur im menüpunkt datei).
